(function(){
'use strict';
const STORAGE='badWorkshopV4';
const cfg=window.BAD_WORKSHOP_CONFIG||{};
const root=document.getElementById('root');
const modalRoot=document.getElementById('modalRoot');
const now=()=>Date.now();
const uid=(p='id')=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=ts=>new Date(ts).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'});
const fmtShortDate=ts=>new Date(ts).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'});
const fmtTime=ts=>new Date(ts).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});
const fmtMoney=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(Number(v)||0))+' грн';
const fmtHours=mins=>`${Math.floor(Math.max(0,mins)/60)} ч ${String(Math.round(Math.max(0,mins)%60)).padStart(2,'0')} мин`;
const dateKey=ts=>{const d=new Date(ts);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const sameDay=(ts,key)=>dateKey(ts)===key;
const startOfToday=()=>{const d=new Date();d.setHours(0,0,0,0);return d.getTime()};
const SHIFT_TYPES={base:'Базовая',project:'Проектная',other:'Другое'};
const EXPENSE_CATS=['Личный транспорт','Такси','Обед','Закупки','Материалы','Парковка','Прочее'];
const DIRECT_COST_CATS=['Транспорт','Обеды','Закупки','Материалы','Аренда','Подрядчики','Прочее'];
const store={get(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')}catch(e){return null}},set(v){try{localStorage.setItem(STORAGE,JSON.stringify(v));return true}catch(e){return false}}};

function seed(){
 const t=now(), day=86400000;
 return {
  version:4,session:null,
  users:[
   {id:'m1',name:'Виктор',email:'boss@bad.work',pin:'1234',role:'manager',approved:true,position:'Руководитель'},
   {id:'e1',name:'Сергей',email:'sergey@bad.work',pin:'1111',role:'employee',approved:true,position:'Монтажник'},
   {id:'e2',name:'Андрей',email:'andrey@bad.work',pin:'2222',role:'employee',approved:true,position:'Постановщик'},
   {id:'e3',name:'Николай',email:'new@bad.work',pin:'3333',role:'employee',approved:false,position:'Монтажник'}
  ],
  projects:[
   {id:'p1',name:'Film 125',active:true,createdBy:'m1',createdAt:t-8*day},
   {id:'p2',name:'Event BMW',active:true,createdBy:'m1',createdAt:t-5*day},
   {id:'p3',name:'Coca-Cola Event',active:true,createdBy:'m1',createdAt:t-3*day}
  ],
  workTypes:['Изготовление','Сборка','Сварка','Столярка','Покраска','Бутафория','Погрузка','Разгрузка','Логистика','Монтаж','Демонтаж','Работа на площадке','Закупка','Прочее'],
  payRules:{
   e1:{standardHours:10,restThreshold:8,shortRestBonus:500,types:{base:{shiftRate:3000,overtimeRate:350},project:{shiftRate:3500,overtimeRate:450},other:{shiftRate:2500,overtimeRate:300}}},
   e2:{standardHours:10,restThreshold:8,shortRestBonus:400,types:{base:{shiftRate:2800,overtimeRate:320},project:{shiftRate:3300,overtimeRate:420},other:{shiftRate:2400,overtimeRate:300}}}
  },
  projectRateOverrides:[
   {id:'ro1',projectId:'p2',employeeId:'e1',shiftType:'project',overtimeRate:500}
  ],
  shifts:[],
  employeePayments:[
   {id:'pay1',employeeId:'e1',date:t-day,amount:3000,comment:'Аванс'}
  ],
  projectCosts:[
   {id:'c1',projectId:'p2',date:t-day,category:'Материалы',amount:2400,comment:'Фанера и крепёж',createdBy:'m1'},
   {id:'c2',projectId:'p1',date:t-2*day,category:'Аренда',amount:1800,comment:'Инструмент',createdBy:'m1'}
  ],
  projectIncome:[
   {id:'i1',projectId:'p2',date:t-4*day,type:'estimate',amount:65000,comment:'Смета проекта'},
   {id:'i2',projectId:'p2',date:t-day,type:'received',amount:30000,comment:'Первый платёж'},
   {id:'i3',projectId:'p1',date:t-3*day,type:'received',amount:25000,comment:'Оплата этапа'}
  ]
 };
}

let state=store.get()||seed();
function migrate(){
 if(!state.version||state.version<4){state=seed();store.set(state);return}
 state.employeePayments=state.employeePayments||[];
 state.projectRateOverrides=state.projectRateOverrides||[];
 state.projectIncome=state.projectIncome||[];
 state.projectCosts=state.projectCosts||[];
 state.shifts=state.shifts||[];
}
migrate();
function save(){store.set(state)}
function userById(id){return state.users.find(x=>x.id===id)}
function projectById(id){return state.projects.find(x=>x.id===id)}
function currentUser(){return userById(state.session)}
function activeShiftFor(id){return state.shifts.find(s=>s.employeeId===id&&s.status==='active')}
function activeSegment(s){return s&&s.segments?s.segments.find(x=>!x.end):null}
function defaultPayRule(){return {standardHours:10,restThreshold:8,shortRestBonus:0,types:{base:{shiftRate:0,overtimeRate:0},project:{shiftRate:0,overtimeRate:0},other:{shiftRate:0,overtimeRate:0}}}}
function ruleFor(id){const r=state.payRules[id]||defaultPayRule();r.standardHours=10;r.types=r.types||defaultPayRule().types;['base','project','other'].forEach(k=>{r.types[k]=r.types[k]||{shiftRate:0,overtimeRate:0}});return r}
function overtimeRateFor(employeeId,projectId,shiftType){const o=state.projectRateOverrides.find(x=>x.employeeId===employeeId&&x.projectId===projectId&&x.shiftType===shiftType);return o?Number(o.overtimeRate||0):Number(ruleFor(employeeId).types[shiftType]?.overtimeRate||0)}
function roundQuarterMinutes(min){return Math.max(0,Math.round(Number(min||0)/15)*15)}
function rawSegmentMinutes(seg,endTs){return Math.max(0,((seg.end||endTs)-seg.start)/60000)}
function shiftRawMinutes(s,endTs){return (s.segments||[]).reduce((a,seg)=>a+rawSegmentMinutes(seg,endTs),0)}
function expenseSum(s){return (s.expenses||[]).reduce((a,e)=>a+Number(e.amount||0),0)}
function previousApprovedOrSubmittedShift(empId,before){return state.shifts.filter(s=>s.employeeId===empId&&s.end&&s.end<before&&s.status!=='active').sort((a,b)=>b.end-a.end)[0]}
function shortRestBonus(s){const r=ruleFor(s.employeeId);if(!r.restThreshold||!r.shortRestBonus)return 0;const prev=previousApprovedOrSubmittedShift(s.employeeId,s.start);if(!prev)return 0;const restH=(s.start-prev.end)/3600000;return restH<Number(r.restThreshold)?Number(r.shortRestBonus||0):0}
function shiftBreakdown(s,endTs){
 endTs=endTs||now();
 const r=ruleFor(s.employeeId), type=s.shiftType||'base', shiftRate=Number(r.types[type]?.shiftRate||0), standardMinutes=600;
 const segs=[...(s.segments||[])].sort((a,b)=>a.start-b.start).map(seg=>({seg,raw:rawSegmentMinutes(seg,endTs)}));
 const rawTotal=segs.reduce((a,x)=>a+x.raw,0), roundedTotal=roundQuarterMinutes(rawTotal), delta=roundedTotal-rawTotal;
 if(segs.length)segs[segs.length-1].paid=Math.max(0,segs[segs.length-1].raw+delta);
 for(let i=0;i<segs.length-1;i++)segs[i].paid=segs[i].raw;
 let elapsed=0,basePay=0,overtimePay=0,overtimeMinutes=0;
 const perProject={};
 segs.forEach(x=>{
   const m=Math.max(0,x.paid||0), baseMin=Math.max(0,Math.min(m,standardMinutes-elapsed)), overMin=Math.max(0,m-baseMin);
   elapsed+=m;
   const hourlyBase=shiftRate/10;
   const overRate=overtimeRateFor(s.employeeId,x.seg.projectId,type);
   const bp=baseMin/60*hourlyBase, op=overMin/60*overRate;
   basePay+=bp;overtimePay+=op;overtimeMinutes+=overMin;
   const p=perProject[x.seg.projectId]||(perProject[x.seg.projectId]={minutes:0,basePay:0,overtimePay:0,overtimeMinutes:0});
   p.minutes+=m;p.basePay+=bp;p.overtimePay+=op;p.overtimeMinutes+=overMin;
 });
 const restBonus=shortRestBonus(s);
 if(restBonus&&roundedTotal>0){Object.keys(perProject).forEach(pid=>{perProject[pid].restBonus=restBonus*(perProject[pid].minutes/roundedTotal)})}
 return {rawMinutes:rawTotal,roundedMinutes:roundedTotal,baseMinutes:Math.min(roundedTotal,standardMinutes),overtimeMinutes,basePay,overtimePay,restBonus,workPay:basePay+overtimePay+restBonus,expenses:expenseSum(s),total:basePay+overtimePay+restBonus+expenseSum(s),perProject};
}
function statusText(s){return s.status==='active'?'Идёт':s.status==='submitted'?'На проверке':s.status==='approved'?'Подтверждена':'Черновик'}
function statusClass(s){return s.status==='active'?'good':s.status==='submitted'?'warn':s.status==='approved'?'blue':''}
function modal(html){modalRoot.innerHTML=`<div class="modal"><div class="sheet"><button class="btn small" id="closeModal" style="float:right">Закрыть</button>${html}</div></div>`;document.getElementById('closeModal').onclick=closeModal}
function closeModal(){modalRoot.innerHTML=''}
function navHTML(role,active){const emp=[['empToday','Сегодня'],['empShifts','Смены'],['empMoney','Деньги'],['empProfile','Профиль']],mgr=[['mgrDash','Сегодня'],['mgrProjects','Проекты'],['mgrPeople','Люди'],['mgrFinance','Финансы'],['mgrAnalytics','Аналитика']];const arr=role==='manager'?mgr:emp;return `<div class="bottom ${role}"><div class="bottom-inner">${arr.map(x=>`<button class="nav ${active===x[0]?'active':''}" data-page="${x[0]}">${x[1]}</button>`).join('')}</div></div>`}
function topHTML(u){return `<div class="top"><div><div class="brand">.B.A.D.Workshop</div><div class="sub">${esc(u.name)} · ${u.role==='manager'?'руководитель':'сотрудник'}</div></div><button class="pill" id="logoutBtn">Выйти</button></div>`}
function attachNav(role){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>renderRole(currentUser(),b.dataset.page));const l=document.getElementById('logoutBtn');if(l)l.onclick=()=>{state.session=null;save();renderApp()}}

function renderApp(){const u=currentUser();if(!u)return renderLogin();if(!u.approved&&u.role==='employee')return renderPending(u);renderRole(u,u.role==='manager'?'mgrDash':'empToday')}
function renderLogin(){root.innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-brand">.B.A.D.Workshop</div><div class="login-tag">Учёт работы мастерской</div><div class="tabs"><button class="tab active" id="loginTab">Вход</button><button class="tab" id="registerTab">Регистрация</button></div><div id="authBox"></div></div></div>`;document.getElementById('loginTab').onclick=()=>showLoginForm();document.getElementById('registerTab').onclick=()=>showRegisterForm();showLoginForm()}
function setAuthTab(which){document.getElementById('loginTab').classList.toggle('active',which==='login');document.getElementById('registerTab').classList.toggle('active',which==='register')}
function showLoginForm(){setAuthTab('login');document.getElementById('authBox').innerHTML=`<div class="field"><label>Email</label><input id="loginEmail" inputmode="email" value="boss@bad.work"></div><div class="field"><label>PIN</label><input id="loginPin" inputmode="numeric" type="password" value="1234"></div><button class="btn primary" id="doLogin">ВОЙТИ</button><div class="notice blue"><b>Демо:</b><br>Руководитель: boss@bad.work / 1234<br>Сотрудник: sergey@bad.work / 1111<br>Ожидает доступа: new@bad.work / 3333</div><div id="authError" class="login-error"></div>`;document.getElementById('doLogin').onclick=()=>{const email=document.getElementById('loginEmail').value.trim().toLowerCase(),pin=document.getElementById('loginPin').value.trim(),u=state.users.find(x=>x.email.toLowerCase()===email&&x.pin===pin);if(!u)return document.getElementById('authError').textContent='Неверный email или PIN';state.session=u.id;save();renderApp()}}
function showRegisterForm(){setAuthTab('register');document.getElementById('authBox').innerHTML=`<div class="notice">Новая регистрация всегда создаёт заявку сотрудника. Роль руководителя назначается только в базе системы.</div><div class="field"><label>Имя</label><input id="regName"></div><div class="field"><label>Должность</label><input id="regPosition"></div><div class="field"><label>Email</label><input id="regEmail" inputmode="email"></div><div class="field"><label>PIN</label><input id="regPin" inputmode="numeric" type="password"></div><button class="btn primary" id="doRegister">ОТПРАВИТЬ ЗАЯВКУ</button><div id="authError" class="login-error"></div>`;document.getElementById('doRegister').onclick=()=>{const name=document.getElementById('regName').value.trim(),email=document.getElementById('regEmail').value.trim().toLowerCase(),pin=document.getElementById('regPin').value.trim();if(!name||!email||!pin)return document.getElementById('authError').textContent='Заполните имя, email и PIN';if(state.users.some(x=>x.email.toLowerCase()===email))return document.getElementById('authError').textContent='Такой email уже зарегистрирован';const u={id:uid('e'),name,email,pin,role:'employee',approved:false,position:document.getElementById('regPosition').value.trim()||'Сотрудник'};state.users.push(u);state.session=u.id;save();renderPending(u)}}
function renderPending(u){root.innerHTML=`<div class="app">${topHTML(u)}<div class="card hero"><div class="label">Доступ</div><div class="big-number" style="margin-top:8px">Ожидает подтверждения</div><div class="muted" style="margin-top:8px">Руководитель должен разрешить использование приложения.</div></div></div>`;document.getElementById('logoutBtn').onclick=()=>{state.session=null;save();renderApp()}}

function renderRole(u,page){if(u.role==='manager')renderManager(u,page);else renderEmployee(u,page)}
function renderEmployee(u,page){root.innerHTML=`<div class="app">${topHTML(u)}<div id="page"></div></div>${navHTML('employee',page)}`;attachNav('employee');if(page==='empToday')renderEmpToday(u);if(page==='empShifts')renderEmpShifts(u);if(page==='empMoney')renderEmpMoney(u);if(page==='empProfile')renderEmpProfile(u)}
function renderEmpToday(u){const box=document.getElementById('page'),s=activeShiftFor(u.id);if(!s){box.innerHTML=`<div class="section-title">Сегодня</div><div class="card hero"><div class="label">Смена не начата</div><div class="big-number" style="margin:10px 0">Готовы к работе?</div><button class="btn primary" id="startShiftBtn">НАЧАТЬ СМЕНУ</button></div>${employeeTodaySummary(u)}`;document.getElementById('startShiftBtn').onclick=()=>openStartShift(u);return}
 const seg=activeSegment(s),c=shiftBreakdown(s,now()),p=seg?projectById(seg.projectId):null;
 box.innerHTML=`<div class="card hero"><div class="label"><span class="badge-dot"></span>Смена идёт</div><div class="timer" id="liveTimer">${fmtHours(c.rawMinutes)}</div><div><b>${esc(p?p.name:'Пауза')}</b></div><div class="muted">${seg?esc(seg.workType):'Пауза'} · тип смены: ${SHIFT_TYPES[s.shiftType||'base']}</div><div class="type-badge">Оплачиваемое время после округления: ${fmtHours(c.roundedMinutes)}</div>${c.overtimeMinutes>0?`<div class="notice good"><b>Переработка ${fmtHours(c.overtimeMinutes)}</b><br>${fmtMoney(c.overtimePay)}</div>`:''}</div><div class="row3"><button class="btn ${seg?'warn':'good'}" id="pauseBtn">${seg?'Пауза':'Продолжить'}</button><button class="btn" id="switchBtn">Сменить работу</button><button class="btn blue" id="shiftTypeBtn">Тип смены</button></div><button class="btn" id="expenseBtn" style="margin-top:9px">+ РАСХОД</button><button class="btn danger" id="finishBtn" style="margin-top:9px">ЗАВЕРШИТЬ СМЕНУ</button><div class="section-title">Расчёт сейчас</div><div class="kpis"><div class="kpi"><span>Основная работа</span><b>${fmtMoney(c.basePay)}</b></div><div class="kpi"><span>Переработка</span><b>${fmtMoney(c.overtimePay)}</b><span class="mini">${fmtHours(c.overtimeMinutes)}</span></div><div class="kpi"><span>Расходы</span><b>${fmtMoney(c.expenses)}</b></div><div class="kpi"><span>Всего к начислению</span><b>${fmtMoney(c.total)}</b></div></div><div class="section-title">Участки смены</div>${segmentsEmployeeHTML(s,true)}`;
 document.getElementById('pauseBtn').onclick=()=>togglePause(u,s);document.getElementById('switchBtn').onclick=()=>openSwitchWork(u,s);document.getElementById('shiftTypeBtn').onclick=()=>openShiftType(s);document.getElementById('expenseBtn').onclick=()=>openExpense(u,s);document.getElementById('finishBtn').onclick=()=>finishEmployeeShift(u,s);document.querySelectorAll('[data-seg-comment]').forEach(b=>b.onclick=()=>openEmployeeSegmentComment(u,s,b.dataset.segComment));
}
function employeeTodaySummary(u){const key=dateKey(now()),shifts=state.shifts.filter(s=>s.employeeId===u.id&&sameDay(s.start,key));const totals=shifts.reduce((a,s)=>{const c=shiftBreakdown(s,s.end||now());a.min+=c.roundedMinutes;a.pay+=c.workPay;a.over+=c.overtimePay;return a},{min:0,pay:0,over:0});return `<div class="kpis"><div class="kpi"><span>Сегодня отработано</span><b>${fmtHours(totals.min)}</b></div><div class="kpi"><span>Начислено</span><b>${fmtMoney(totals.pay)}</b></div></div>`}
function openStartShift(u){const projects=state.projects.filter(p=>p.active);modal(`<h3>Начать смену</h3><div class="field"><label>Проект</label><select id="startProject">${projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Тип смены</label><select id="startType">${Object.keys(SHIFT_TYPES).map(k=>`<option value="${k}">${SHIFT_TYPES[k]}</option>`).join('')}</select></div><div class="field"><label>Вид работы</label><select id="startWork">${state.workTypes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>Комментарий руководителю (необязательно)</label><textarea id="startComment"></textarea></div><div class="field"><label>Приватная заметка (видна только вам)</label><textarea id="startPrivate"></textarea></div><button class="btn primary" id="confirmStart">НАЧАТЬ</button>`);document.getElementById('confirmStart').onclick=()=>{const s={id:uid('s'),employeeId:u.id,start:now(),end:null,status:'active',shiftType:document.getElementById('startType').value,segments:[],expenses:[]};s.segments.push({id:uid('seg'),projectId:document.getElementById('startProject').value,workType:document.getElementById('startWork').value,start:s.start,end:null,employeeComment:document.getElementById('startComment').value.trim(),managerReply:'',privateNote:document.getElementById('startPrivate').value.trim()});state.shifts.push(s);save();closeModal();renderEmployee(u,'empToday')}}
function togglePause(u,s){const seg=activeSegment(s);if(seg){seg.end=now();save();renderEmployee(u,'empToday')}else openSwitchWork(u,s)}
function openSwitchWork(u,s){const projects=state.projects.filter(p=>p.active);modal(`<h3>${activeSegment(s)?'Сменить работу':'Продолжить работу'}</h3><div class="field"><label>Проект</label><select id="swProject">${projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Вид работы</label><select id="swWork">${state.workTypes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>Комментарий руководителю</label><textarea id="swComment"></textarea></div><div class="field"><label>Приватная заметка</label><textarea id="swPrivate"></textarea></div><button class="btn primary" id="confirmSwitch">НАЧАТЬ УЧАСТОК</button>`);document.getElementById('confirmSwitch').onclick=()=>{const old=activeSegment(s);if(old)old.end=now();s.segments.push({id:uid('seg'),projectId:document.getElementById('swProject').value,workType:document.getElementById('swWork').value,start:now(),end:null,employeeComment:document.getElementById('swComment').value.trim(),managerReply:'',privateNote:document.getElementById('swPrivate').value.trim()});save();closeModal();renderEmployee(u,'empToday')}}
function openShiftType(s){modal(`<h3>Тип смены</h3><div class="notice">Тип применяется ко всей текущей смене. Стоимость задаёт руководитель отдельно для каждого сотрудника.</div>${Object.keys(SHIFT_TYPES).map(k=>`<button class="btn ${s.shiftType===k?'primary':''}" data-type="${k}" style="margin-top:8px">${SHIFT_TYPES[k]}</button>`).join('')}`);document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{s.shiftType=b.dataset.type;save();closeModal();renderEmployee(currentUser(),'empToday')})}
function openExpense(u,s){modal(`<h3>Новый расход</h3><div class="field"><label>Проект</label><select id="expProject">${state.projects.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Категория</label><select id="expCat">${EXPENSE_CATS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Сумма, грн</label><input id="expAmount" type="number" inputmode="decimal"></div><div class="field"><label>Комментарий</label><textarea id="expComment" placeholder="Маршрут, что куплено, где был обед и т. п."></textarea></div><button class="btn primary" id="saveExpense">СОХРАНИТЬ</button>`);document.getElementById('saveExpense').onclick=()=>{const amount=Number(document.getElementById('expAmount').value);if(!amount)return;s.expenses.push({id:uid('e'),projectId:document.getElementById('expProject').value,category:document.getElementById('expCat').value,amount,comment:document.getElementById('expComment').value.trim(),status:'pending',date:now()});save();closeModal();renderEmployee(u,'empToday')}}
function openEmployeeSegmentComment(u,s,segId){const seg=s.segments.find(x=>x.id===segId);if(!seg)return;modal(`<h3>Комментарий к участку</h3><div class="field"><label>Комментарий руководителю</label><textarea id="pubComment">${esc(seg.employeeComment||'')}</textarea></div>${seg.managerReply?`<div class="comment manager"><strong>Ответ руководителя</strong>${esc(seg.managerReply)}</div>`:''}<div class="field"><label>Приватная заметка — только для вас</label><textarea id="privateNote">${esc(seg.privateNote||'')}</textarea></div><button class="btn primary" id="saveSegComment">СОХРАНИТЬ</button>`);document.getElementById('saveSegComment').onclick=()=>{seg.employeeComment=document.getElementById('pubComment').value.trim();seg.privateNote=document.getElementById('privateNote').value.trim();save();closeModal();renderEmployee(u,'empToday')}}
function segmentsEmployeeHTML(s,editable){return `<div class="timeline">${(s.segments||[]).map(seg=>`<div class="segment"><div class="item"><div class="item-head"><div><b>${esc(projectById(seg.projectId)?.name||'Проект')}</b><div class="muted">${esc(seg.workType)} · ${fmtTime(seg.start)}–${seg.end?fmtTime(seg.end):'сейчас'}</div></div>${editable?`<button class="btn small" data-seg-comment="${seg.id}">Комментарий</button>`:''}</div>${seg.employeeComment?`<div class="comment"><strong>Для руководителя</strong>${esc(seg.employeeComment)}</div>`:''}${seg.managerReply?`<div class="comment manager"><strong>Ответ руководителя</strong>${esc(seg.managerReply)}</div>`:''}${seg.privateNote?`<div class="comment private"><strong>Приватно</strong>${esc(seg.privateNote)}</div>`:''}</div></div>`).join('')}</div>`}
function finishEmployeeShift(u,s){const seg=activeSegment(s);if(seg)seg.end=now();s.end=now();const c=shiftBreakdown(s,s.end);modal(`<h3>Завершение смены</h3><div class="card"><div class="statline"><span>Фактически</span><b>${fmtHours(c.rawMinutes)}</b></div><div class="statline"><span>После округления 15 мин</span><b>${fmtHours(c.roundedMinutes)}</b></div><div class="statline"><span>Основная работа</span><b>${fmtMoney(c.basePay)}</b></div><div class="statline"><span>Переработка ${fmtHours(c.overtimeMinutes)}</span><b>${fmtMoney(c.overtimePay)}</b></div>${c.restBonus?`<div class="statline"><span>Короткий межсменный отдых</span><b>${fmtMoney(c.restBonus)}</b></div>`:''}<div class="statline"><span>Расходы к возмещению</span><b>${fmtMoney(c.expenses)}</b></div><hr class="divider"><div class="statline big-number"><span>Итого</span><b>${fmtMoney(c.total)}</b></div></div><button class="btn primary" id="submitShift">ОТПРАВИТЬ РУКОВОДИТЕЛЮ</button><button class="btn" id="cancelFinish" style="margin-top:8px">Вернуться</button>`);document.getElementById('cancelFinish').onclick=()=>{s.end=null;if(s.segments.length&&!activeSegment(s)){s.segments[s.segments.length-1].end=null}closeModal();renderEmployee(u,'empToday')};document.getElementById('submitShift').onclick=()=>{s.status='submitted';save();closeModal();renderEmployee(u,'empToday')}}
function renderEmpShifts(u){const shifts=state.shifts.filter(s=>s.employeeId===u.id).sort((a,b)=>b.start-a.start);document.getElementById('page').innerHTML=`<div class="section-title">Мои смены</div><div class="list">${shifts.length?shifts.map(s=>{const c=shiftBreakdown(s,s.end||now());return `<div class="item clickable" data-emp-shift="${s.id}"><div class="item-head"><div><b>${fmtDate(s.start)}</b><div class="muted">${SHIFT_TYPES[s.shiftType||'base']} · ${fmtHours(c.roundedMinutes)}</div></div><span class="status ${statusClass(s)}">${statusText(s)}</span></div><div class="statline"><span>Работа</span><b>${fmtMoney(c.workPay)}</b></div>${c.overtimeMinutes?`<div class="statline"><span>Переработка</span><b>${fmtHours(c.overtimeMinutes)} · ${fmtMoney(c.overtimePay)}</b></div>`:''}</div>`}).join(''):'<div class="empty">Смен пока нет</div>'}</div>`;document.querySelectorAll('[data-emp-shift]').forEach(b=>b.onclick=()=>openEmployeeShiftDetail(u,b.dataset.empShift))}
function openEmployeeShiftDetail(u,id){const s=state.shifts.find(x=>x.id===id);if(!s)return;const c=shiftBreakdown(s,s.end||now());modal(`<h3>Смена ${fmtDate(s.start)}</h3><div class="muted">${fmtTime(s.start)}–${s.end?fmtTime(s.end):'сейчас'} · ${SHIFT_TYPES[s.shiftType||'base']} · ${statusText(s)}</div>${segmentsEmployeeHTML(s,false)}<div class="card"><div class="statline"><span>Оплачиваемое время</span><b>${fmtHours(c.roundedMinutes)}</b></div><div class="statline"><span>Основная работа</span><b>${fmtMoney(c.basePay)}</b></div><div class="statline"><span>Переработка</span><b>${fmtHours(c.overtimeMinutes)} · ${fmtMoney(c.overtimePay)}</b></div><div class="statline"><span>Расходы</span><b>${fmtMoney(c.expenses)}</b></div></div>`)}
function employeeLedger(empId){const approved=state.shifts.filter(s=>s.employeeId===empId&&s.status==='approved');let earned=0,expenses=0;approved.forEach(s=>{const c=shiftBreakdown(s,s.end||now());earned+=c.workPay;expenses+=c.expenses});const paid=state.employeePayments.filter(p=>p.employeeId===empId).reduce((a,p)=>a+Number(p.amount||0),0);return {earned,expenses,paid,due:earned+expenses-paid}}
function renderEmpMoney(u){const l=employeeLedger(u.id),payments=state.employeePayments.filter(p=>p.employeeId===u.id).sort((a,b)=>b.date-a.date);document.getElementById('page').innerHTML=`<div class="section-title">Деньги</div><div class="kpis"><div class="kpi"><span>Заработано</span><b>${fmtMoney(l.earned)}</b></div><div class="kpi"><span>Расходы к возврату</span><b>${fmtMoney(l.expenses)}</b></div><div class="kpi"><span>Выплачено</span><b>${fmtMoney(l.paid)}</b></div><div class="kpi"><span>Осталось</span><b class="${l.due>0?'red':'green'}">${fmtMoney(l.due)}</b></div></div><div class="section-title">Выплаты</div><div class="list">${payments.length?payments.map(p=>`<div class="item"><div class="item-head"><div><b>${fmtShortDate(p.date)}</b><div class="muted">${esc(p.comment||'Выплата')}</div></div><div class="money">${fmtMoney(p.amount)}</div></div></div>`).join(''):'<div class="empty">Выплат пока нет</div>'}</div>`}
function renderEmpProfile(u){const r=ruleFor(u.id);document.getElementById('page').innerHTML=`<div class="section-title">Профиль</div><div class="card"><b>${esc(u.name)}</b><div class="muted">${esc(u.position||'Сотрудник')}</div></div><div class="section-title">Условия оплаты</div>${Object.keys(SHIFT_TYPES).map(k=>`<div class="item"><div class="item-head"><b>${SHIFT_TYPES[k]}</b><span class="status">10 ч = полная ставка</span></div><div class="statline"><span>Полная ставка</span><b>${fmtMoney(r.types[k].shiftRate)}</b></div><div class="statline"><span>Переработка после 10 ч</span><b>${fmtMoney(r.types[k].overtimeRate)}/ч</b></div></div>`).join('')}<div class="notice">До 10 часов оплата считается пропорционально фактически отработанному времени. Время округляется к ближайшим 15 минутам: 7 минут не засчитывается, 8 минут засчитывается как 15.</div>`}

function renderManager(u,page){root.innerHTML=`<div class="app">${topHTML(u)}<div id="page"></div></div>${navHTML('manager',page)}`;attachNav('manager');if(page==='mgrDash')renderMgrDash(u);if(page==='mgrProjects')renderMgrProjects(u);if(page==='mgrPeople')renderMgrPeople(u);if(page==='mgrFinance')renderMgrFinance(u);if(page==='mgrAnalytics')renderMgrAnalytics(u)}
function renderMgrDash(u){const page=document.getElementById('page'),active=state.shifts.filter(s=>s.status==='active'),submitted=state.shifts.filter(s=>s.status==='submitted'),today=dateKey(now());let todayPay=0,todayExpense=0;state.shifts.filter(s=>sameDay(s.start,today)).forEach(s=>{const c=shiftBreakdown(s,s.end||now());todayPay+=c.workPay;todayExpense+=c.expenses});page.innerHTML=`<div class="section-title">Оперативная сводка</div><div class="section-sub">Обновлено ${fmtTime(now())}. Пока экран открыт, данные пересчитываются каждую минуту.</div><div class="kpis"><div class="kpi"><span>Работают сейчас</span><b>${active.length}</b></div><div class="kpi"><span>Смен на проверке</span><b>${submitted.length}</b></div><div class="kpi"><span>Начислено сегодня</span><b>${fmtMoney(todayPay)}</b></div><div class="kpi"><span>Расходы сотрудников</span><b>${fmtMoney(todayExpense)}</b></div></div><div class="section-title">Сейчас работают</div><div class="list">${active.length?active.map(s=>managerActiveCard(s)).join(''):'<div class="empty">Сейчас никто не работает</div>'}</div><div class="section-title">На проверке</div><div class="list">${submitted.length?submitted.map(s=>managerSubmittedCard(s)).join(''):'<div class="empty">Нет смен на проверке</div>'}</div><div class="section-title">Сегодня по проектам</div>${projectSummaryCards('today')}`;document.querySelectorAll('[data-open-shift]').forEach(b=>b.onclick=()=>openManagerShift(b.dataset.openShift))}
function managerActiveCard(s){const emp=userById(s.employeeId),seg=activeSegment(s),c=shiftBreakdown(s,now());return `<div class="item clickable" data-open-shift="${s.id}"><div class="item-head"><div><b><span class="badge-dot"></span>${esc(emp?.name||'')}</b><div class="muted">${esc(projectById(seg?.projectId)?.name||'Пауза')} · ${seg?esc(seg.workType):'Пауза'}</div></div><span class="status good">${fmtHours(c.roundedMinutes)}</span></div><div class="statline"><span>${SHIFT_TYPES[s.shiftType||'base']}</span><b>${fmtMoney(c.workPay)}</b></div>${c.overtimeMinutes?`<div class="statline"><span>Переработка</span><b>${fmtHours(c.overtimeMinutes)} · ${fmtMoney(c.overtimePay)}</b></div>`:''}</div>`}
function managerSubmittedCard(s){const emp=userById(s.employeeId),c=shiftBreakdown(s,s.end||now());return `<div class="item clickable" data-open-shift="${s.id}"><div class="item-head"><div><b>${esc(emp?.name||'')}</b><div class="muted">${fmtDate(s.start)} · ${SHIFT_TYPES[s.shiftType||'base']} · ${fmtHours(c.roundedMinutes)}</div></div><span class="status warn">Проверить</span></div><div class="statline"><span>Работа</span><b>${fmtMoney(c.workPay)}</b></div><div class="statline"><span>Расходы</span><b>${fmtMoney(c.expenses)}</b></div></div>`}
function publicSegmentHTML(seg){return `${seg.employeeComment?`<div class="comment"><strong>Комментарий сотрудника</strong>${esc(seg.employeeComment)}</div>`:''}${seg.managerReply?`<div class="comment manager"><strong>Ответ руководителя</strong>${esc(seg.managerReply)}</div>`:''}`}
function openManagerShift(id){const s=state.shifts.find(x=>x.id===id);if(!s)return;const emp=userById(s.employeeId),c=shiftBreakdown(s,s.end||now());modal(`<h3>${esc(emp?.name||'Сотрудник')} · ${fmtDate(s.start)}</h3><div class="muted">${fmtTime(s.start)}–${s.end?fmtTime(s.end):'сейчас'} · ${SHIFT_TYPES[s.shiftType||'base']} · ${statusText(s)}</div><div class="timeline" style="margin-top:16px">${s.segments.map(seg=>`<div class="segment"><div class="item"><div class="item-head"><div><b>${esc(projectById(seg.projectId)?.name||'Проект')}</b><div class="muted">${esc(seg.workType)} · ${fmtTime(seg.start)}–${seg.end?fmtTime(seg.end):'сейчас'}</div></div><button class="btn small blue" data-reply-seg="${seg.id}">Ответить</button></div>${publicSegmentHTML(seg)}</div></div>`).join('')}</div><div class="card"><div class="statline"><span>Оплачиваемое время</span><b>${fmtHours(c.roundedMinutes)}</b></div><div class="statline"><span>Основная работа</span><b>${fmtMoney(c.basePay)}</b></div><div class="statline"><span>Переработка ${fmtHours(c.overtimeMinutes)}</span><b>${fmtMoney(c.overtimePay)}</b></div>${c.restBonus?`<div class="statline"><span>Короткий отдых</span><b>${fmtMoney(c.restBonus)}</b></div>`:''}<div class="statline"><span>Расходы сотрудника</span><b>${fmtMoney(c.expenses)}</b></div><hr class="divider"><div class="statline"><span><b>Итого</b></span><b class="big-number">${fmtMoney(c.total)}</b></div></div>${s.status==='submitted'?`<button class="btn good" id="approveShiftBtn">ПОДТВЕРДИТЬ СМЕНУ</button>`:''}`);document.querySelectorAll('[data-reply-seg]').forEach(b=>b.onclick=()=>openManagerSegmentReply(b.dataset.replySeg));const a=document.getElementById('approveShiftBtn');if(a)a.onclick=()=>{s.status='approved';(s.expenses||[]).forEach(e=>e.status='approved');save();closeModal();renderManager(currentUser(),'mgrDash')}}
function openManagerSegmentReply(segId){let seg=null;for(const s of state.shifts){const f=s.segments.find(x=>x.id===segId);if(f){seg=f;break}}if(!seg)return;modal(`<h3>Ответ сотруднику</h3>${seg.employeeComment?`<div class="comment"><strong>Комментарий сотрудника</strong>${esc(seg.employeeComment)}</div>`:'<div class="notice">Публичного комментария нет.</div>'}<div class="field"><label>Ответ руководителя</label><textarea id="mgrReply">${esc(seg.managerReply||'')}</textarea></div><button class="btn primary" id="saveMgrReply">СОХРАНИТЬ ОТВЕТ</button>`);document.getElementById('saveMgrReply').onclick=()=>{seg.managerReply=document.getElementById('mgrReply').value.trim();save();closeModal();renderManager(currentUser(),'mgrDash')}}

function renderMgrProjects(u){const page=document.getElementById('page');page.innerHTML=`<div class="section-title">Проекты</div><button class="btn primary" id="addProjectBtn">+ НОВЫЙ ПРОЕКТ</button><div class="list" style="margin-top:10px">${state.projects.map(p=>projectManagerCard(p)).join('')}</div>`;document.getElementById('addProjectBtn').onclick=()=>openAddProject(u);document.querySelectorAll('[data-project-toggle]').forEach(b=>b.onclick=()=>{const p=projectById(b.dataset.projectToggle);p.active=!p.active;save();renderMgrProjects(u)});document.querySelectorAll('[data-project-cost]').forEach(b=>b.onclick=()=>openProjectCost(u,b.dataset.projectCost));document.querySelectorAll('[data-project-income]').forEach(b=>b.onclick=()=>openProjectIncome(u,b.dataset.projectIncome));document.querySelectorAll('[data-project-rates]').forEach(b=>b.onclick=()=>openProjectRates(b.dataset.projectRates));document.querySelectorAll('[data-project-report]').forEach(b=>b.onclick=()=>openProjectReport(b.dataset.projectReport))}
function projectManagerCard(p){const a=projectAnalytics(p.id,'all');return `<div class="item"><div class="item-head"><div><b>${esc(p.name)}</b><div class="muted">${p.active?'Активный':'Завершён'}</div></div><span class="status ${p.active?'good':''}">${p.active?'В работе':'Закрыт'}</span></div><div class="statline"><span>Получено</span><b>${fmtMoney(a.received)}</b></div><div class="statline"><span>Затраты</span><b>${fmtMoney(a.totalCosts)}</b></div><div class="toolbar" style="margin-top:9px"><button class="btn small blue" data-project-report="${p.id}">Сводка</button><button class="btn small" data-project-cost="${p.id}">+ Затрата</button><button class="btn small" data-project-income="${p.id}">+ Доход</button><button class="btn small" data-project-rates="${p.id}">Переработки</button><button class="btn small ${p.active?'warn':'good'}" data-project-toggle="${p.id}">${p.active?'Завершить':'Возобновить'}</button></div></div>`}
function openAddProject(u){modal(`<h3>Новый проект</h3><div class="field"><label>Название</label><input id="newProjectName"></div><button class="btn primary" id="saveProject">СОЗДАТЬ</button>`);document.getElementById('saveProject').onclick=()=>{const name=document.getElementById('newProjectName').value.trim();if(!name)return;state.projects.push({id:uid('p'),name,active:true,createdBy:u.id,createdAt:now()});save();closeModal();renderMgrProjects(u)}}
function openProjectCost(u,pid){modal(`<h3>Затрата проекта</h3><div class="field"><label>Проект</label><select id="costProject">${state.projects.map(p=>`<option value="${p.id}" ${p.id===pid?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Категория</label><select id="costCat">${DIRECT_COST_CATS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Сумма, грн</label><input id="costAmount" type="number" inputmode="decimal"></div><div class="field"><label>Комментарий</label><textarea id="costComment"></textarea></div><button class="btn primary" id="saveCost">СОХРАНИТЬ</button>`);document.getElementById('saveCost').onclick=()=>{const amount=Number(document.getElementById('costAmount').value);if(!amount)return;state.projectCosts.push({id:uid('c'),projectId:document.getElementById('costProject').value,date:now(),category:document.getElementById('costCat').value,amount,comment:document.getElementById('costComment').value.trim(),createdBy:u.id});save();closeModal();renderMgrProjects(u)}}
function openProjectIncome(u,pid){modal(`<h3>Деньги проекта</h3><div class="field"><label>Проект</label><select id="incomeProject">${state.projects.map(p=>`<option value="${p.id}" ${p.id===pid?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Тип</label><select id="incomeType"><option value="estimate">Смета / плановая сумма</option><option value="received">Фактически получено</option></select></div><div class="field"><label>Сумма, грн</label><input id="incomeAmount" type="number" inputmode="decimal"></div><div class="field"><label>Комментарий</label><textarea id="incomeComment"></textarea></div><button class="btn primary" id="saveIncome">СОХРАНИТЬ</button>`);document.getElementById('saveIncome').onclick=()=>{const amount=Number(document.getElementById('incomeAmount').value);if(!amount)return;state.projectIncome.push({id:uid('i'),projectId:document.getElementById('incomeProject').value,date:now(),type:document.getElementById('incomeType').value,amount,comment:document.getElementById('incomeComment').value.trim(),createdBy:u.id});save();closeModal();renderMgrProjects(u)}}
function openProjectRates(pid){const p=projectById(pid),emps=state.users.filter(x=>x.role==='employee'&&x.approved);modal(`<h3>Переработки · ${esc(p?.name||'')}</h3><div class="notice">Можно задать ставку переработки для конкретного сотрудника и типа смены именно на этом проекте. Если поле пустое — используется ставка из профиля сотрудника.</div><div class="field"><label>Сотрудник</label><select id="rateEmp">${emps.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></div><div class="field"><label>Тип смены</label><select id="rateType">${Object.keys(SHIFT_TYPES).map(k=>`<option value="${k}">${SHIFT_TYPES[k]}</option>`).join('')}</select></div><div class="field"><label>Переработка, грн/час</label><input id="rateOver" type="number" inputmode="decimal"></div><button class="btn primary" id="saveProjectRate">СОХРАНИТЬ СТАВКУ</button><div class="section-title">Текущие ставки проекта</div><div class="list">${state.projectRateOverrides.filter(x=>x.projectId===pid).map(x=>`<div class="item"><b>${esc(userById(x.employeeId)?.name||'')}</b><div class="muted">${SHIFT_TYPES[x.shiftType]} · ${fmtMoney(x.overtimeRate)}/ч</div></div>`).join('')||'<div class="empty">Отдельных ставок пока нет</div>'}</div>`);document.getElementById('saveProjectRate').onclick=()=>{const employeeId=document.getElementById('rateEmp').value,shiftType=document.getElementById('rateType').value,overtimeRate=Number(document.getElementById('rateOver').value);if(!overtimeRate)return;let r=state.projectRateOverrides.find(x=>x.projectId===pid&&x.employeeId===employeeId&&x.shiftType===shiftType);if(r)r.overtimeRate=overtimeRate;else state.projectRateOverrides.push({id:uid('ro'),projectId:pid,employeeId,shiftType,overtimeRate});save();closeModal();openProjectRates(pid)}}

function renderMgrPeople(u){const pending=state.users.filter(x=>x.role==='employee'&&!x.approved),approved=state.users.filter(x=>x.role==='employee'&&x.approved);document.getElementById('page').innerHTML=`<div class="section-title">Доступ к приложению</div><div class="list">${pending.length?pending.map(x=>`<div class="item"><div class="item-head"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.position)} · ${esc(x.email)}</div></div><span class="status warn">Ожидает</span></div><div class="row" style="margin-top:9px"><button class="btn small good" data-approve-user="${x.id}">Разрешить</button><button class="btn small danger" data-reject-user="${x.id}">Отклонить</button></div></div>`).join(''):'<div class="empty">Новых заявок нет</div>'}</div><div class="section-title">Сотрудники</div><div class="list">${approved.map(x=>employeeManagerCard(x)).join('')}</div>`;document.querySelectorAll('[data-approve-user]').forEach(b=>b.onclick=()=>{const x=userById(b.dataset.approveUser);x.approved=true;state.payRules[x.id]=state.payRules[x.id]||defaultPayRule();save();renderMgrPeople(u)});document.querySelectorAll('[data-reject-user]').forEach(b=>b.onclick=()=>{state.users=state.users.filter(x=>x.id!==b.dataset.rejectUser);save();renderMgrPeople(u)});document.querySelectorAll('[data-payrule]').forEach(b=>b.onclick=()=>openPayRule(b.dataset.payrule));document.querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>openEmployeePayment(b.dataset.payment));document.querySelectorAll('[data-emp-report]').forEach(b=>b.onclick=()=>openEmployeeReport(b.dataset.empReport))}
function employeeManagerCard(x){const l=employeeLedger(x.id),s=activeShiftFor(x.id);return `<div class="item"><div class="item-head"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.position)} ${s?'· сейчас работает':''}</div></div><span class="status ${s?'good':''}">${s?'Работает':'Сотрудник'}</span></div><div class="statline"><span>Заработано</span><b>${fmtMoney(l.earned)}</b></div><div class="statline"><span>Выплачено</span><b>${fmtMoney(l.paid)}</b></div><div class="statline"><span>Осталось</span><b>${fmtMoney(l.due)}</b></div><div class="toolbar"><button class="btn small" data-payrule="${x.id}">Условия оплаты</button><button class="btn small good" data-payment="${x.id}">+ Выплата</button><button class="btn small blue" data-emp-report="${x.id}">Сводка</button></div></div>`}
function openPayRule(empId){const x=userById(empId),r=ruleFor(empId);modal(`<h3>Оплата · ${esc(x?.name||'')}</h3><div class="notice">Норма полной смены фиксирована: 10 часов. До 10 часов оплата пропорциональна времени; после 10 часов включается ставка переработки.</div>${Object.keys(SHIFT_TYPES).map(k=>`<div class="card"><b>${SHIFT_TYPES[k]}</b><div class="field"><label>Полная ставка за 10 часов, грн</label><input id="shift_${k}" type="number" inputmode="decimal" value="${r.types[k].shiftRate}"></div><div class="field"><label>Переработка по умолчанию, грн/час</label><input id="over_${k}" type="number" inputmode="decimal" value="${r.types[k].overtimeRate}"></div></div>`).join('')}<div class="field"><label>Минимальный межсменный отдых, часов</label><input id="restHours" type="number" inputmode="decimal" value="${r.restThreshold||8}"></div><div class="field"><label>Доплата за короткий отдых, грн</label><input id="restBonus" type="number" inputmode="decimal" value="${r.shortRestBonus||0}"></div><button class="btn primary" id="savePayRule">СОХРАНИТЬ</button>`);document.getElementById('savePayRule').onclick=()=>{const nr={standardHours:10,restThreshold:Number(document.getElementById('restHours').value)||0,shortRestBonus:Number(document.getElementById('restBonus').value)||0,types:{}};Object.keys(SHIFT_TYPES).forEach(k=>nr.types[k]={shiftRate:Number(document.getElementById('shift_'+k).value)||0,overtimeRate:Number(document.getElementById('over_'+k).value)||0});state.payRules[empId]=nr;save();closeModal();renderMgrPeople(currentUser())}}
function openEmployeePayment(empId){const x=userById(empId),l=employeeLedger(empId);modal(`<h3>Выплата · ${esc(x?.name||'')}</h3><div class="notice good">Сейчас осталось к выплате: <b>${fmtMoney(l.due)}</b></div><div class="field"><label>Сумма, грн</label><input id="paymentAmount" type="number" inputmode="decimal"></div><div class="field"><label>Комментарий</label><input id="paymentComment" placeholder="Аванс, зарплата за неделю и т. п."></div><button class="btn primary" id="savePayment">ЗАПИСАТЬ ВЫПЛАТУ</button>`);document.getElementById('savePayment').onclick=()=>{const amount=Number(document.getElementById('paymentAmount').value);if(!amount)return;state.employeePayments.push({id:uid('pay'),employeeId:empId,date:now(),amount,comment:document.getElementById('paymentComment').value.trim()});save();closeModal();renderMgrPeople(currentUser())}}

function renderMgrFinance(u){const payments=[...state.employeePayments].sort((a,b)=>b.date-a.date),income=[...state.projectIncome].sort((a,b)=>b.date-a.date);document.getElementById('page').innerHTML=`<div class="section-title">Финансы</div><div class="row"><button class="btn good" id="financePayment">+ Выплата сотруднику</button><button class="btn blue" id="financeIncome">+ Деньги проекта</button></div><div class="section-title">Последние выплаты сотрудникам</div><div class="list">${payments.length?payments.slice(0,12).map(p=>`<div class="item"><div class="item-head"><div><b>${esc(userById(p.employeeId)?.name||'')}</b><div class="muted">${fmtDate(p.date)} · ${esc(p.comment||'Выплата')}</div></div><div class="money">${fmtMoney(p.amount)}</div></div></div>`).join(''):'<div class="empty">Выплат нет</div>'}</div><div class="section-title">Деньги проектов</div><div class="list">${income.length?income.slice(0,12).map(i=>`<div class="item"><div class="item-head"><div><b>${esc(projectById(i.projectId)?.name||'')}</b><div class="muted">${fmtDate(i.date)} · ${i.type==='received'?'Получено':'Смета'}</div></div><div class="money">${fmtMoney(i.amount)}</div></div>${i.comment?`<div class="comment">${esc(i.comment)}</div>`:''}</div>`).join(''):'<div class="empty">Записей нет</div>'}</div>`;document.getElementById('financePayment').onclick=()=>openPaymentPicker();document.getElementById('financeIncome').onclick=()=>openProjectIncome(u,state.projects[0]?.id)}
function openPaymentPicker(){const emps=state.users.filter(x=>x.role==='employee'&&x.approved);modal(`<h3>Кому выплата?</h3><div class="field"><select id="paymentEmp">${emps.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></div><button class="btn primary" id="choosePaymentEmp">ДАЛЕЕ</button>`);document.getElementById('choosePaymentEmp').onclick=()=>{const id=document.getElementById('paymentEmp').value;closeModal();openEmployeePayment(id)}}

function periodMatch(ts,period){return period==='today'?sameDay(ts,dateKey(now())):true}
function projectAnalytics(projectId,period){let labor=0,employeeExpenses=0,received=0,estimate=0,direct=0;const categories={Сотрудники:0,'Личный транспорт':0,Такси:0,Обед:0,Закупки:0,Материалы:0,Парковка:0,Транспорт:0,Аренда:0,Подрядчики:0,Прочее:0};const employees={};state.shifts.filter(s=>s.status==='approved'||s.status==='submitted'||s.status==='active').forEach(s=>{const c=shiftBreakdown(s,s.end||now()),pp=c.perProject[projectId];if(pp&&periodMatch(s.start,period)){const shareBonus=pp.restBonus||0,lp=pp.basePay+pp.overtimePay+shareBonus;labor+=lp;categories.Сотрудники+=lp;employees[s.employeeId]=(employees[s.employeeId]||0)+lp}(s.expenses||[]).forEach(e=>{if(e.projectId===projectId&&periodMatch(e.date||s.start,period)){employeeExpenses+=Number(e.amount||0);categories[e.category]=(categories[e.category]||0)+Number(e.amount||0)}})});state.projectCosts.filter(c=>c.projectId===projectId&&periodMatch(c.date,period)).forEach(c=>{direct+=Number(c.amount||0);categories[c.category]=(categories[c.category]||0)+Number(c.amount||0)});state.projectIncome.filter(i=>i.projectId===projectId&&periodMatch(i.date,period)).forEach(i=>{if(i.type==='received')received+=Number(i.amount||0);else estimate+=Number(i.amount||0)});const totalCosts=labor+employeeExpenses+direct;return {labor,employeeExpenses,direct,received,estimate,totalCosts,balance:received-totalCosts,categories,employees}}
function globalAnalytics(period){let received=0,estimate=0,totalCosts=0,labor=0,employeeExpenses=0,direct=0;state.projects.forEach(p=>{const a=projectAnalytics(p.id,period);received+=a.received;estimate+=a.estimate;totalCosts+=a.totalCosts;labor+=a.labor;employeeExpenses+=a.employeeExpenses;direct+=a.direct});const paid=state.employeePayments.filter(p=>periodMatch(p.date,period)).reduce((a,p)=>a+Number(p.amount||0),0),owed=state.users.filter(x=>x.role==='employee'&&x.approved).reduce((a,e)=>a+Math.max(0,employeeLedger(e.id).due),0);return {received,estimate,totalCosts,labor,employeeExpenses,direct,paid,owed,balance:received-totalCosts}}
function projectSummaryCards(period){return `<div class="list">${state.projects.map(p=>{const a=projectAnalytics(p.id,period);return `<div class="item"><div class="item-head"><b>${esc(p.name)}</b><span class="status ${a.balance>=0?'good':'danger'}">${period==='today'?'Сегодня':'Всего'}</span></div><div class="row"><div><div class="mini muted">Получено</div><b>${fmtMoney(a.received)}</b></div><div><div class="mini muted">Затраты</div><b>${fmtMoney(a.totalCosts)}</b></div></div></div>`}).join('')}</div>`}
function renderMgrAnalytics(u){document.getElementById('page').innerHTML=`<div class="section-title">Расширенная аналитика</div><div class="filterbar"><button class="chip active" data-period="all">За всё время</button><button class="chip" data-period="today">Сегодня</button></div><div id="analyticsBody"></div>`;let period='all';const draw=()=>{const g=globalAnalytics(period);document.getElementById('analyticsBody').innerHTML=`<div class="section-title">Баланс мастерской</div><div class="kpis"><div class="kpi"><span>Получено от проектов</span><b>${fmtMoney(g.received)}</b></div><div class="kpi"><span>Сметная сумма</span><b>${fmtMoney(g.estimate)}</b></div><div class="kpi"><span>Все затраты</span><b>${fmtMoney(g.totalCosts)}</b></div><div class="kpi"><span>Баланс</span><b class="${g.balance>=0?'positive':'negative'}">${fmtMoney(g.balance)}</b></div></div><div class="card"><div class="statline"><span>Сотрудники</span><b>${fmtMoney(g.labor)}</b></div><div class="statline"><span>Расходы сотрудников</span><b>${fmtMoney(g.employeeExpenses)}</b></div><div class="statline"><span>Прямые расходы проектов</span><b>${fmtMoney(g.direct)}</b></div><div class="statline"><span>Выплачено сотрудникам</span><b>${fmtMoney(g.paid)}</b></div><div class="statline"><span>Текущий долг сотрудникам</span><b>${fmtMoney(g.owed)}</b></div></div><div class="section-title">По проектам</div><div class="list">${state.projects.map(p=>analyticsProjectCard(p,period)).join('')}</div><div class="section-title">По сотрудникам</div><div class="list">${state.users.filter(x=>x.role==='employee'&&x.approved).map(e=>analyticsEmployeeCard(e)).join('')}</div><div class="notice">Экспорт в Excel/CSV логично добавить следующим этапом — структура данных для него уже есть.</div>`;document.querySelectorAll('[data-an-project]').forEach(b=>b.onclick=()=>openProjectReport(b.dataset.anProject,period));document.querySelectorAll('[data-an-employee]').forEach(b=>b.onclick=()=>openEmployeeReport(b.dataset.anEmployee))};document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x.dataset.period===period));draw()});draw()}
function analyticsProjectCard(p,period){const a=projectAnalytics(p.id,period);return `<div class="item clickable" data-an-project="${p.id}"><div class="item-head"><b>${esc(p.name)}</b><span class="status ${a.balance>=0?'good':'danger'}">${fmtMoney(a.balance)}</span></div><div class="statline"><span>Получено</span><b>${fmtMoney(a.received)}</b></div><div class="statline"><span>Затраты</span><b>${fmtMoney(a.totalCosts)}</b></div></div>`}
function analyticsEmployeeCard(e){const l=employeeLedger(e.id);return `<div class="item clickable" data-an-employee="${e.id}"><div class="item-head"><b>${esc(e.name)}</b><span class="status">${esc(e.position)}</span></div><div class="statline"><span>Заработано</span><b>${fmtMoney(l.earned)}</b></div><div class="statline"><span>Выплачено</span><b>${fmtMoney(l.paid)}</b></div><div class="statline"><span>Осталось</span><b>${fmtMoney(l.due)}</b></div></div>`}
function openProjectReport(pid,period='all'){const p=projectById(pid),a=projectAnalytics(pid,period);const cats=Object.entries(a.categories).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);const emps=Object.entries(a.employees).sort((a,b)=>b[1]-a[1]);modal(`<h3>${esc(p?.name||'Проект')}</h3><div class="muted">${period==='today'?'Сегодня':'За всё время'}</div><div class="kpis"><div class="kpi"><span>Получено</span><b>${fmtMoney(a.received)}</b></div><div class="kpi"><span>Смета</span><b>${fmtMoney(a.estimate)}</b></div><div class="kpi"><span>Затраты</span><b>${fmtMoney(a.totalCosts)}</b></div><div class="kpi"><span>Баланс</span><b class="${a.balance>=0?'positive':'negative'}">${fmtMoney(a.balance)}</b></div></div><div class="section-title">Затраты по статьям</div><div class="list">${cats.length?cats.map(([k,v])=>`<div class="item"><div class="item-head"><b>${esc(k)}</b><div class="money">${fmtMoney(v)}</div></div></div>`).join(''):'<div class="empty">Затрат нет</div>'}</div><div class="section-title">Сотрудники проекта</div><div class="list">${emps.length?emps.map(([id,v])=>`<div class="item"><div class="item-head"><b>${esc(userById(id)?.name||'')}</b><div class="money">${fmtMoney(v)}</div></div></div>`).join(''):'<div class="empty">Начислений нет</div>'}</div>`)}
function openEmployeeReport(empId){const e=userById(empId),l=employeeLedger(empId),shifts=state.shifts.filter(s=>s.employeeId===empId&&s.status==='approved').sort((a,b)=>b.start-a.start);const byProject={};shifts.forEach(s=>{const c=shiftBreakdown(s,s.end||now());Object.entries(c.perProject).forEach(([pid,v])=>{byProject[pid]=(byProject[pid]||0)+v.basePay+v.overtimePay+(v.restBonus||0)})});modal(`<h3>${esc(e?.name||'Сотрудник')}</h3><div class="kpis"><div class="kpi"><span>Заработано</span><b>${fmtMoney(l.earned)}</b></div><div class="kpi"><span>Расходы</span><b>${fmtMoney(l.expenses)}</b></div><div class="kpi"><span>Выплачено</span><b>${fmtMoney(l.paid)}</b></div><div class="kpi"><span>Осталось</span><b>${fmtMoney(l.due)}</b></div></div><div class="section-title">По проектам</div><div class="list">${Object.entries(byProject).sort((a,b)=>b[1]-a[1]).map(([pid,v])=>`<div class="item"><div class="item-head"><b>${esc(projectById(pid)?.name||'')}</b><div class="money">${fmtMoney(v)}</div></div></div>`).join('')||'<div class="empty">Подтверждённых смен нет</div>'}</div><div class="section-title">Последние смены</div><div class="list">${shifts.slice(0,10).map(s=>{const c=shiftBreakdown(s,s.end);return `<div class="item"><div class="item-head"><div><b>${fmtDate(s.start)}</b><div class="muted">${SHIFT_TYPES[s.shiftType||'base']} · ${fmtHours(c.roundedMinutes)}</div></div><div class="money">${fmtMoney(c.workPay)}</div></div></div>`}).join('')||'<div class="empty">Нет данных</div>'}</div>`)}

function updateNetworkBadge(){const b=document.getElementById('offlineBadge');if(b)b.classList.toggle('hidden',navigator.onLine)}
window.addEventListener('online',updateNetworkBadge);window.addEventListener('offline',updateNetworkBadge);updateNetworkBadge();
if('serviceWorker' in navigator&&/^https?:/.test(location.protocol))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
setInterval(()=>{const u=currentUser();if(!u)return;const active=document.querySelector('.nav.active')?.dataset.page;if(u.role==='manager'&&active==='mgrDash')renderMgrDash(u);if(u.role==='employee'&&active==='empToday')renderEmpToday(u)},60000);
renderApp();
})();
