(function(){
'use strict';

const cfg=window.BAD_WORKSHOP_CONFIG||{};
const root=document.getElementById('root');
const modalRoot=document.getElementById('modalRoot');
const SHIFT_TYPES={base:'Базовая',project:'Проектная',other:'Другое'};
const WORK_TYPES=['Изготовление','Сборка','Сварка','Столярка','Покраска','Бутафория','Погрузка','Разгрузка','Логистика','Монтаж','Демонтаж','Работа на площадке','Закупка','Прочее'];
const EMPLOYEE_EXPENSE_CATS=['Личный транспорт','Такси','Обед','Закупки','Материалы','Парковка','Прочее'];
const ANALYTICS_CATS=['Сотрудники','Транспорт','Обеды','Закупки','Материалы','Парковка','Аренда','Подрядчики','Прочее'];
const DIRECT_COST_CATS=['Транспорт','Обеды','Закупки','Материалы','Парковка','Аренда','Подрядчики','Прочее'];
const EXPENSE_DEFAULT_MAP={'Личный транспорт':'Транспорт','Такси':'Транспорт','Обед':'Обеды','Закупки':'Закупки','Материалы':'Материалы','Парковка':'Парковка','Прочее':'Прочее'};
const PRIORITY_LABEL={high:'Высокий',normal:'Обычный',low:'Низкий'};
const PRIORITY_ORDER={high:0,normal:1,low:2};
const now=()=>new Date();
const isoNow=()=>new Date().toISOString();
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>new Date(v).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'});
const fmtShortDate=v=>new Date(v).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'});
const fmtTime=v=>new Date(v).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});
const fmtMoney=v=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:0,maximumFractionDigits:2}).format(Number(v)||0)+' грн';
const fmtHours=m=>{m=Math.max(0,Math.round(Number(m)||0));return `${Math.floor(m/60)} ч ${String(m%60).padStart(2,'0')} мин`};
const dateKey=v=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const sameDay=(v,key=dateKey(new Date()))=>dateKey(v)===key;
const roundQuarter=m=>Math.max(0,Math.round((Number(m)||0)/15)*15);
const minutesBetween=(a,b)=>Math.max(0,(new Date(b)-new Date(a))/60000);
const isConfigured=()=>cfg.supabaseUrl&&cfg.supabasePublishableKey&&!String(cfg.supabaseUrl).includes('PASTE_')&&!String(cfg.supabasePublishableKey).includes('PASTE_');
let sb=null;
let refreshTimer=null;
let minuteTimer=null;
let state={session:null,profile:null,profiles:[],projects:[],payRules:[],projectRates:[],shifts:[],segments:[],privateNotes:[],expenses:[],payments:[],projectMoney:[],projectCosts:[],todos:[],page:null,realtime:null,lastSync:null};

function modal(html){modalRoot.innerHTML=`<div class="modal"><div class="sheet"><button class="btn small" id="closeModal" style="float:right">Закрыть</button>${html}</div></div>`;document.getElementById('closeModal').onclick=closeModal}
function closeModal(){modalRoot.innerHTML=''}
function toast(msg,kind='blue'){const id='toast_'+Date.now();document.body.insertAdjacentHTML('beforeend',`<div id="${id}" style="position:fixed;left:50%;bottom:105px;transform:translateX(-50%);z-index:100;background:${kind==='danger'?'#aa2d26':'#111318'};color:#fff;padding:10px 14px;border-radius:999px;font-size:12px;max-width:88%;text-align:center">${esc(msg)}</div>`);setTimeout(()=>document.getElementById(id)?.remove(),2600)}
function profileById(id){return state.profiles.find(x=>x.id===id)||(state.profile?.id===id?state.profile:null)}
function projectById(id){return state.projects.find(x=>x.id===id)}
function shiftById(id){return state.shifts.find(x=>x.id===id)}
function segmentsFor(shiftId){return state.segments.filter(x=>x.shift_id===shiftId).sort((a,b)=>new Date(a.started_at)-new Date(b.started_at))}
function expensesFor(shiftId){return state.expenses.filter(x=>x.shift_id===shiftId).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at))}
function privateNoteFor(segmentId){return state.privateNotes.find(x=>x.segment_id===segmentId)?.note||''}
function activeShiftFor(empId){return state.shifts.find(s=>s.employee_id===empId&&s.status==='active')}
function activeSegmentFor(shiftId){return segmentsFor(shiftId).find(s=>!s.ended_at)}
function payRuleFor(empId){return state.payRules.find(x=>x.employee_id===empId)||{employee_id:empId,standard_hours:10,rest_threshold_hours:8,short_rest_bonus:0,base_shift_rate:0,base_overtime_rate:0,project_shift_rate:0,project_overtime_rate:0,other_shift_rate:0,other_overtime_rate:0}}
function rateFields(type){return type==='project'?['project_shift_rate','project_overtime_rate']:type==='other'?['other_shift_rate','other_overtime_rate']:['base_shift_rate','base_overtime_rate']}
function segmentBaseRate(seg){if(seg.manager_base_rate_override!=null&&seg.manager_base_rate_override!=='')return Number(seg.manager_base_rate_override)||0;const r=payRuleFor(shiftById(seg.shift_id)?.employee_id),f=rateFields(seg.shift_type||'base')[0];return Number(r[f])||0}
function segmentOvertimeRate(seg){if(seg.manager_overtime_rate_override!=null&&seg.manager_overtime_rate_override!=='')return Number(seg.manager_overtime_rate_override)||0;const sh=shiftById(seg.shift_id);const over=state.projectRates.find(x=>x.project_id===seg.project_id&&x.employee_id===sh?.employee_id&&x.shift_type===(seg.shift_type||'base'));if(over)return Number(over.overtime_rate)||0;const r=payRuleFor(sh?.employee_id),f=rateFields(seg.shift_type||'base')[1];return Number(r[f])||0}
function previousShift(empId,before){return state.shifts.filter(s=>s.employee_id===empId&&s.ended_at&&new Date(s.ended_at)<new Date(before)&&s.status!=='rejected').sort((a,b)=>new Date(b.ended_at)-new Date(a.ended_at))[0]}
function shortRestBonus(sh){const r=payRuleFor(sh.employee_id),threshold=Number(r.rest_threshold_hours)||0,bonus=Number(r.short_rest_bonus)||0;if(!threshold||!bonus)return 0;const prev=previousShift(sh.employee_id,sh.started_at);if(!prev)return 0;return minutesBetween(prev.ended_at,sh.started_at)<threshold*60?bonus:0}

function shiftCalc(sh,endAt){
 const segs=segmentsFor(sh.id).map(seg=>({seg,raw:minutesBetween(seg.started_at,seg.ended_at||endAt||isoNow())}));
 const raw=segs.reduce((a,x)=>a+x.raw,0), rounded=roundQuarter(raw), delta=rounded-raw;
 segs.forEach(x=>x.paid=x.raw);if(segs.length)segs[segs.length-1].paid=Math.max(0,segs[segs.length-1].paid+delta);
 let elapsed=0,basePay=0,overtimePay=0,overtimeMinutes=0;const perProject={};
 const standard=(Number(payRuleFor(sh.employee_id).standard_hours)||10)*60;
 segs.forEach(x=>{
   const m=x.paid,baseMin=Math.max(0,Math.min(m,standard-elapsed)),overMin=Math.max(0,m-baseMin);elapsed+=m;
   const bp=baseMin/60*(segmentBaseRate(x.seg)/10),op=overMin/60*segmentOvertimeRate(x.seg);
   basePay+=bp;overtimePay+=op;overtimeMinutes+=overMin;
   const p=perProject[x.seg.project_id]||(perProject[x.seg.project_id]={minutes:0,basePay:0,overtimePay:0,overtimeMinutes:0});
   p.minutes+=m;p.basePay+=bp;p.overtimePay+=op;p.overtimeMinutes+=overMin;
 });
 const restBonus=shortRestBonus(sh);if(restBonus&&rounded){Object.values(perProject).forEach(p=>p.restBonus=restBonus*(p.minutes/rounded))}
 const exps=expensesFor(sh.id),expenseApproved=exps.filter(e=>e.status==='approved').reduce((a,e)=>a+Number(e.amount||0),0),expensePending=exps.filter(e=>e.status==='pending').reduce((a,e)=>a+Number(e.amount||0),0),expenseVisible=exps.filter(e=>e.status!=='rejected').reduce((a,e)=>a+Number(e.amount||0),0);
 return {rawMinutes:raw,roundedMinutes:rounded,baseMinutes:Math.min(rounded,standard),overtimeMinutes,basePay,overtimePay,restBonus,workPay:basePay+overtimePay+restBonus,expenseApproved,expensePending,expenseVisible,totalVisible:basePay+overtimePay+restBonus+expenseVisible,perProject};
}

function employeeLedger(empId){let earned=0,approvedExpenses=0,pending=0;state.shifts.filter(s=>s.employee_id===empId).forEach(s=>{const c=shiftCalc(s,s.ended_at||isoNow());if(s.status==='approved'){earned+=c.workPay;approvedExpenses+=c.expenseApproved}else if(s.status==='submitted'){pending+=c.workPay+c.expenseVisible}});const paid=state.payments.filter(p=>p.employee_id===empId).reduce((a,p)=>a+Number(p.amount||0),0);return {earned,approvedExpenses,pending,paid,due:earned+approvedExpenses-paid}}
function statusText(s){return s.status==='active'?'Идёт':s.status==='submitted'?'На проверке':s.status==='approved'?'Подтверждена':'Отклонена'}
function statusClass(s){return s.status==='active'?'good':s.status==='submitted'?'warn':s.status==='approved'?'blue':'danger'}
function typeOptions(selected){return Object.entries(SHIFT_TYPES).map(([k,v])=>`<option value="${k}" ${selected===k?'selected':''}>${v}</option>`).join('')}
function projectOptions(selected,activeOnly=false){return state.projects.filter(p=>!activeOnly||p.active).map(p=>`<option value="${p.id}" ${selected===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}
function workOptions(selected){return WORK_TYPES.map(x=>`<option ${selected===x?'selected':''}>${esc(x)}</option>`).join('')}

async function q(promise,context='Операция'){
 const {data,error}=await promise;if(error){console.error(context,error);throw new Error(error.message||context)}return data;
}
async function loadAll(){
 const role=state.profile?.role;const queries=[
  q(sb.from('projects').select('*').order('created_at',{ascending:false}),'Проекты'),
  q(sb.from('pay_rules').select('*'),'Тарифы'),
  q(sb.from('project_overtime_rates').select('*'),'Ставки проектов'),
  q(sb.from('shifts').select('*').order('started_at',{ascending:false}).limit(role==='manager'?1000:300),'Смены'),
  q(sb.from('shift_segments').select('*').order('started_at',{ascending:true}).limit(role==='manager'?5000:1500),'Участки'),
  q(sb.from('segment_private_notes').select('*'),'Приватные заметки'),
  q(sb.from('expenses').select('*').order('created_at',{ascending:false}).limit(role==='manager'?3000:1000),'Расходы'),
  q(sb.from('employee_payments').select('*').order('paid_at',{ascending:false}).limit(role==='manager'?2000:500),'Выплаты'),
  q(sb.from('todos').select('*').order('position',{ascending:true}).order('created_at',{ascending:true}).limit(1000),'Дела')
 ];
 if(role==='manager'){
  queries.push(q(sb.from('profiles').select('*').order('created_at',{ascending:true}),'Сотрудники'));
  queries.push(q(sb.from('project_money').select('*').order('entry_at',{ascending:false}).limit(2000),'Деньги проектов'));
  queries.push(q(sb.from('project_costs').select('*').order('cost_at',{ascending:false}).limit(3000),'Затраты проектов'));
 }
 const r=await Promise.all(queries);let i=0;
 state.projects=r[i++]||[];state.payRules=r[i++]||[];state.projectRates=r[i++]||[];state.shifts=r[i++]||[];state.segments=r[i++]||[];state.privateNotes=r[i++]||[];state.expenses=r[i++]||[];state.payments=r[i++]||[];state.todos=r[i++]||[];
 if(role==='manager'){state.profiles=r[i++]||[];state.projectMoney=r[i++]||[];state.projectCosts=r[i++]||[]}else{state.profiles=[state.profile];state.projectMoney=[];state.projectCosts=[]}
 state.lastSync=new Date();
}

async function init(){
 if(!isConfigured())return renderSetup();
 if(!window.supabase?.createClient)return renderFatal('Не загрузилась библиотека Supabase. Проверьте интернет и перезагрузите страницу.');
 sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 const {data}=await sb.auth.getSession();state.session=data.session||null;
 sb.auth.onAuthStateChange((_event,session)=>{state.session=session||null;if(!session){cleanupRealtime();state.profile=null;renderAuth()}});
 if(!state.session)return renderAuth();await enterSession();
}
async function enterSession(){
 try{
  state.profile=await q(sb.from('profiles').select('*').eq('id',state.session.user.id).single(),'Профиль');
  if(!state.profile.approved)return renderPending();
  await loadAll();setupRealtime();renderRole(state.profile.role==='manager'?'mgrDash':'empToday');
  clearInterval(minuteTimer);minuteTimer=setInterval(async()=>{if(!state.session||!navigator.onLine)return;try{await loadAll();renderRole(state.page|| (state.profile.role==='manager'?'mgrDash':'empToday'),false)}catch(e){}},60000);
 }catch(e){renderFatal('Не удалось загрузить данные: '+e.message)}
}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{if(!state.session)return;try{await loadAll();renderRole(state.page|| (state.profile.role==='manager'?'mgrDash':'empToday'),false)}catch(e){console.error(e)}},500)}
function setupRealtime(){cleanupRealtime();const tables=['profiles','projects','pay_rules','project_overtime_rates','shifts','shift_segments','expenses','employee_payments','project_money','project_costs','todos'];let ch=sb.channel('bad-workshop-live');tables.forEach(t=>{ch=ch.on('postgres_changes',{event:'*',schema:'public',table:t},scheduleRefresh)});state.realtime=ch.subscribe()}
function cleanupRealtime(){if(state.realtime&&sb)sb.removeChannel(state.realtime).catch(()=>{});state.realtime=null}

function renderSetup(){root.innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-brand">.B.A.D.Workshop</div><div class="login-tag">Серверная версия v5</div><div class="notice">Сервер ещё не подключён. Откройте <b>config.js</b> в GitHub и вставьте Project URL и Publishable key вашего проекта Supabase.</div><div class="card"><b>Дальше:</b><div class="muted" style="margin-top:8px">1. Создать проект Supabase<br>2. Выполнить файл supabase-schema.sql<br>3. Вставить два значения в config.js<br>4. Обновить GitHub Pages</div></div></div></div>`}
function renderFatal(msg){root.innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-brand">.B.A.D.Workshop</div><div class="notice">${esc(msg)}</div><button class="btn primary" onclick="location.reload()">ПОВТОРИТЬ</button></div></div>`}
function renderAuth(){state.page=null;root.innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-brand">.B.A.D.Workshop</div><div class="login-tag">Работа мастерской</div><div class="tabs"><button class="tab active" id="loginTab">Вход</button><button class="tab" id="registerTab">Регистрация</button></div><div id="authBox"></div></div></div>`;document.getElementById('loginTab').onclick=()=>showLogin();document.getElementById('registerTab').onclick=()=>showRegister();showLogin()}
function setAuthTab(name){document.getElementById('loginTab').classList.toggle('active',name==='login');document.getElementById('registerTab').classList.toggle('active',name==='register')}
function showLogin(){setAuthTab('login');document.getElementById('authBox').innerHTML=`<div class="field"><label>Email</label><input id="authEmail" type="email" autocomplete="email"></div><div class="field"><label>Пароль</label><input id="authPassword" type="password" autocomplete="current-password"></div><button class="btn primary" id="authLogin">ВОЙТИ</button><div id="authError" class="login-error"></div>`;document.getElementById('authLogin').onclick=async()=>{const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;document.getElementById('authError').textContent='';try{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;state.session=data.session;await enterSession()}catch(e){document.getElementById('authError').textContent=e.message}}}
function showRegister(){setAuthTab('register');document.getElementById('authBox').innerHTML=`<div class="notice">Роль выбирать не нужно. Новая регистрация создаётся как сотрудник и начинает работать только после подтверждения руководителем.</div><div class="field"><label>Имя и фамилия</label><input id="regName"></div><div class="field"><label>Email</label><input id="regEmail" type="email"></div><div class="field"><label>Пароль (минимум 6 символов)</label><input id="regPassword" type="password"></div><button class="btn primary" id="authRegister">СОЗДАТЬ АККАУНТ</button><div id="authError" class="login-error"></div>`;document.getElementById('authRegister').onclick=async()=>{const full_name=document.getElementById('regName').value.trim(),email=document.getElementById('regEmail').value.trim(),password=document.getElementById('regPassword').value;if(!full_name||!email||password.length<6){document.getElementById('authError').textContent='Заполните имя, email и пароль от 6 символов';return}try{const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name}}});if(error)throw error;if(data.session){state.session=data.session;await enterSession()}else{document.getElementById('authBox').innerHTML=`<div class="notice good">Регистрация создана. Если в Supabase включено подтверждение email — откройте письмо, затем войдите. После этого доступ подтвердит руководитель.</div><button class="btn" id="backLogin">К ВХОДУ</button>`;document.getElementById('backLogin').onclick=showLogin}}catch(e){document.getElementById('authError').textContent=e.message}}}
function renderPending(){root.innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-brand">.B.A.D.Workshop</div><div class="notice">${esc(state.profile.full_name||'Сотрудник')}, регистрация получена. Доступ к приложению должен подтвердить руководитель.</div><button class="btn primary" id="pendingRefresh">ПРОВЕРИТЬ ДОСТУП</button><button class="btn" id="pendingLogout" style="margin-top:8px">ВЫЙТИ</button></div></div>`;document.getElementById('pendingRefresh').onclick=async()=>{state.profile=await q(sb.from('profiles').select('*').eq('id',state.session.user.id).single(),'Профиль');if(state.profile.approved)await enterSession();else toast('Пока ожидает подтверждения')};document.getElementById('pendingLogout').onclick=()=>sb.auth.signOut()}

function topHTML(){return `<div class="top"><div><div class="brand">.B.A.D.Workshop</div><div class="sub">${esc(state.profile.full_name||state.session.user.email)} · ${state.profile.role==='manager'?'руководитель':'сотрудник'}</div></div><button class="pill" id="logoutBtn">Выйти</button></div>`}
function navHTML(page){const emp=[['empToday','Сегодня'],['empShifts','Смены'],['empMoney','Деньги'],['empProfile','Профиль']],mgr=[['mgrDash','Сегодня'],['mgrProjects','Проекты'],['mgrPeople','Люди'],['mgrFinance','Финансы'],['mgrAnalytics','Аналитика']];const arr=state.profile.role==='manager'?mgr:emp;return `<div class="bottom ${state.profile.role}"><div class="bottom-inner">${arr.map(([id,l])=>`<button class="nav ${page===id?'active':''}" data-page="${id}">${l}</button>`).join('')}</div></div>`}
function renderRole(page,full=true){state.page=page;if(full)root.innerHTML=`<div class="app">${topHTML()}<div id="page"></div><div class="sync">${state.lastSync?'Синхронизировано '+fmtTime(state.lastSync):''}</div></div>${navHTML(page)}`;else{const n=document.querySelectorAll('.nav');n.forEach(x=>x.classList.toggle('active',x.dataset.page===page))}const map={empToday:renderEmpToday,empShifts:renderEmpShifts,empMoney:renderEmpMoney,empProfile:renderEmpProfile,mgrDash:renderMgrDash,mgrProjects:renderMgrProjects,mgrPeople:renderMgrPeople,mgrFinance:renderMgrFinance,mgrAnalytics:renderMgrAnalytics};map[page]?.();document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>renderRole(b.dataset.page));const out=document.getElementById('logoutBtn');if(out)out.onclick=()=>sb.auth.signOut()}

// ---------- Employee ----------
function renderEmpToday(){const sh=activeShiftFor(state.profile.id),page=document.getElementById('page');if(!sh){page.innerHTML=`<div class="section-title">Сегодня</div><div class="row"><button class="btn primary" id="startShift">НАЧАТЬ СМЕНУ</button><button class="btn blue" id="openTodos">ДЕЛА</button></div>${employeeTodaySummary()}`;document.getElementById('startShift').onclick=openStartShift;document.getElementById('openTodos').onclick=()=>openTodos(false);return}
 const c=shiftCalc(sh,isoNow()),seg=activeSegmentFor(sh.id),p=seg?projectById(seg.project_id):null;
 page.innerHTML=`<div class="card hero"><div class="label"><span class="badge-dot"></span>Смена идёт</div><div class="timer">${fmtHours(c.rawMinutes)}</div><div><b>${esc(p?.name||'Пауза')}</b></div><div class="muted">${seg?esc(seg.work_type)+' · '+SHIFT_TYPES[seg.shift_type||'base']:'Пауза'}</div><div class="type-badge">После округления: ${fmtHours(c.roundedMinutes)}</div>${c.overtimeMinutes?`<div class="notice good"><b>Переработка ${fmtHours(c.overtimeMinutes)}</b><br>${fmtMoney(c.overtimePay)}</div>`:''}</div><div class="row3"><button class="btn ${seg?'warn':'good'}" id="pauseBtn">${seg?'Пауза':'Продолжить'}</button><button class="btn" id="switchBtn">Сменить работу</button><button class="btn blue" id="todoBtn">Дела</button></div><button class="btn" id="expenseBtn" style="margin-top:9px">+ РАСХОД</button><button class="btn danger" id="finishBtn" style="margin-top:9px">ЗАВЕРШИТЬ СМЕНУ</button><div class="section-title">Расчёт сейчас</div><div class="kpis"><div class="kpi"><span>Основная работа</span><b>${fmtMoney(c.basePay)}</b></div><div class="kpi"><span>Переработка</span><b>${fmtMoney(c.overtimePay)}</b><span class="mini">${fmtHours(c.overtimeMinutes)}</span></div><div class="kpi"><span>Расходы</span><b>${fmtMoney(c.expenseVisible)}</b></div><div class="kpi"><span>Всего предварительно</span><b>${fmtMoney(c.totalVisible)}</b></div></div><div class="section-title">Участки смены</div>${employeeSegmentsHTML(sh)}`;
 document.getElementById('pauseBtn').onclick=()=>togglePause(sh);document.getElementById('switchBtn').onclick=()=>openSwitchWork(sh);document.getElementById('todoBtn').onclick=()=>openTodos(false);document.getElementById('expenseBtn').onclick=()=>openExpense(sh);document.getElementById('finishBtn').onclick=()=>finishShift(sh);document.querySelectorAll('[data-edit-emp-seg]').forEach(b=>b.onclick=()=>openEmployeeSegmentComment(b.dataset.editEmpSeg));
}
function employeeTodaySummary(){const today=state.shifts.filter(s=>s.employee_id===state.profile.id&&sameDay(s.started_at));let mins=0,pay=0;today.forEach(s=>{const c=shiftCalc(s,s.ended_at||isoNow());mins+=c.roundedMinutes;pay+=c.workPay});const todoOpen=state.todos.filter(t=>t.assignee_id===state.profile.id&&!t.completed).length;return `<div class="section-title">Сегодня</div><div class="kpis"><div class="kpi"><span>Оплачиваемое время</span><b>${fmtHours(mins)}</b></div><div class="kpi"><span>Работа</span><b>${fmtMoney(pay)}</b></div><div class="kpi"><span>Открытых дел</span><b>${todoOpen}</b></div><div class="kpi"><span>Синхронизация</span><b style="font-size:14px">онлайн</b></div></div>`}
function employeeSegmentsHTML(sh){const ss=segmentsFor(sh.id);return ss.length?`<div class="timeline">${ss.map(s=>`<div class="segment"><div class="item-head"><div><b>${fmtTime(s.started_at)}–${s.ended_at?fmtTime(s.ended_at):'сейчас'}</b><div class="muted">${esc(projectById(s.project_id)?.name||'')} · ${esc(s.work_type)} · ${SHIFT_TYPES[s.shift_type||'base']}</div></div><button class="btn small" data-edit-emp-seg="${s.id}">Комментарий</button></div>${s.employee_comment?`<div class="comment"><strong>Сотрудник</strong>${esc(s.employee_comment)}</div>`:''}${s.manager_reply?`<div class="comment manager"><strong>Руководитель</strong>${esc(s.manager_reply)}</div>`:''}${privateNoteFor(s.id)?`<div class="comment private"><strong>Приватная заметка</strong>${esc(privateNoteFor(s.id))}</div>`:''}</div>`).join('')}</div>`:'<div class="empty">Участков нет</div>'}
function openStartShift(){if(!state.projects.some(p=>p.active))return toast('Нет активных проектов','danger');modal(`<h3>Начать смену</h3><div class="field"><label>Проект</label><select id="stProject">${projectOptions(null,true)}</select></div><div class="field"><label>Тип смены</label><select id="stType">${typeOptions('base')}</select></div><div class="field"><label>Вид работы</label><select id="stWork">${workOptions()}</select></div><div class="field"><label>Комментарий руководителю</label><textarea id="stComment"></textarea></div><div class="field"><label>Приватная заметка</label><textarea id="stPrivate"></textarea></div><button class="btn primary" id="stSave">НАЧАТЬ</button>`);document.getElementById('stSave').onclick=async()=>{try{const [sh]=await q(sb.from('shifts').insert({employee_id:state.profile.id,started_at:isoNow(),status:'active'}).select(),'Старт смены');const [seg]=await q(sb.from('shift_segments').insert({shift_id:sh.id,project_id:document.getElementById('stProject').value,work_type:document.getElementById('stWork').value,shift_type:document.getElementById('stType').value,employee_comment:document.getElementById('stComment').value.trim(),started_at:sh.started_at}).select(),'Участок смены');const note=document.getElementById('stPrivate').value.trim();if(note)await q(sb.from('segment_private_notes').insert({segment_id:seg.id,employee_id:state.profile.id,note}),'Приватная заметка');closeModal();await loadAll();renderRole('empToday')}catch(e){toast(e.message,'danger')}}}
async function togglePause(sh){const seg=activeSegmentFor(sh.id);try{if(seg){await q(sb.from('shift_segments').update({ended_at:isoNow()}).eq('id',seg.id),'Пауза');await loadAll();renderRole('empToday')}else openSwitchWork(sh)}catch(e){toast(e.message,'danger')}}
function openSwitchWork(sh){const old=activeSegmentFor(sh.id);modal(`<h3>${old?'Сменить участок':'Продолжить работу'}</h3><div class="field"><label>Проект</label><select id="swProject">${projectOptions(old?.project_id,true)}</select></div><div class="field"><label>Тип смены</label><select id="swType">${typeOptions(old?.shift_type||'base')}</select></div><div class="field"><label>Вид работы</label><select id="swWork">${workOptions(old?.work_type)}</select></div><div class="field"><label>Комментарий руководителю</label><textarea id="swComment"></textarea></div><div class="field"><label>Приватная заметка</label><textarea id="swPrivate"></textarea></div><button class="btn primary" id="swSave">НАЧАТЬ УЧАСТОК</button>`);document.getElementById('swSave').onclick=async()=>{try{const t=isoNow();if(old)await q(sb.from('shift_segments').update({ended_at:t}).eq('id',old.id),'Закрытие участка');const [seg]=await q(sb.from('shift_segments').insert({shift_id:sh.id,project_id:document.getElementById('swProject').value,work_type:document.getElementById('swWork').value,shift_type:document.getElementById('swType').value,employee_comment:document.getElementById('swComment').value.trim(),started_at:t}).select(),'Новый участок');const note=document.getElementById('swPrivate').value.trim();if(note)await q(sb.from('segment_private_notes').insert({segment_id:seg.id,employee_id:state.profile.id,note}),'Приватная заметка');closeModal();await loadAll();renderRole('empToday')}catch(e){toast(e.message,'danger')}}}
function openEmployeeSegmentComment(id){const seg=state.segments.find(x=>x.id===id);if(!seg)return;modal(`<h3>Комментарий к участку</h3><div class="field"><label>Комментарий руководителю</label><textarea id="ecPublic">${esc(seg.employee_comment||'')}</textarea></div><div class="field"><label>Приватная заметка — только вам</label><textarea id="ecPrivate">${esc(privateNoteFor(id))}</textarea></div>${seg.manager_reply?`<div class="comment manager"><strong>Ответ руководителя</strong>${esc(seg.manager_reply)}</div>`:''}<button class="btn primary" id="ecSave">СОХРАНИТЬ</button>`);document.getElementById('ecSave').onclick=async()=>{try{await q(sb.from('shift_segments').update({employee_comment:document.getElementById('ecPublic').value.trim()}).eq('id',id),'Комментарий');const note=document.getElementById('ecPrivate').value.trim();if(note)await q(sb.from('segment_private_notes').upsert({segment_id:id,employee_id:state.profile.id,note}),'Приватная заметка');else await sb.from('segment_private_notes').delete().eq('segment_id',id);closeModal();await loadAll();renderRole('empToday')}catch(e){toast(e.message,'danger')}}}
function openExpense(sh){modal(`<h3>Новый расход</h3><div class="field"><label>Проект</label><select id="exProject">${projectOptions(activeSegmentFor(sh.id)?.project_id,true)}</select></div><div class="field"><label>Тип расхода</label><select id="exCat">${EMPLOYEE_EXPENSE_CATS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Сумма, грн</label><input id="exAmount" type="number" inputmode="decimal"></div><div class="field"><label>Комментарий</label><textarea id="exComment" placeholder="Маршрут, что куплено, где был обед и т. п."></textarea></div><div class="notice">Руководитель увидит расход и при проверке сможет отнести его к нужной статье аналитики.</div><button class="btn primary" id="exSave">СОХРАНИТЬ</button>`);document.getElementById('exSave').onclick=async()=>{const amount=Number(document.getElementById('exAmount').value),cat=document.getElementById('exCat').value;if(!(amount>0))return toast('Укажите сумму','danger');try{await q(sb.from('expenses').insert({shift_id:sh.id,employee_id:state.profile.id,project_id:document.getElementById('exProject').value,employee_category:cat,analytics_category:EXPENSE_DEFAULT_MAP[cat]||'Прочее',amount,comment:document.getElementById('exComment').value.trim(),status:'pending'}),'Расход');closeModal();await loadAll();renderRole('empToday')}catch(e){toast(e.message,'danger')}}}
async function finishShift(sh){if(!confirm('Завершить смену и отправить руководителю?'))return;try{const t=isoNow(),seg=activeSegmentFor(sh.id);if(seg)await q(sb.from('shift_segments').update({ended_at:t}).eq('id',seg.id),'Закрытие участка');await q(sb.from('shifts').update({ended_at:t,status:'submitted'}).eq('id',sh.id),'Завершение смены');await loadAll();renderRole('empToday');toast('Смена отправлена руководителю')}catch(e){toast(e.message,'danger')}}
function renderEmpShifts(){const list=state.shifts.filter(s=>s.employee_id===state.profile.id);document.getElementById('page').innerHTML=`<div class="section-title">Мои смены</div><div class="list">${list.length?list.map(s=>{const c=shiftCalc(s,s.ended_at||isoNow());return `<div class="item clickable" data-es="${s.id}"><div class="item-head"><div><b>${fmtDate(s.started_at)}</b><div class="muted">${fmtHours(c.roundedMinutes)}</div></div><span class="status ${statusClass(s)}">${statusText(s)}</span></div><div class="statline"><span>Работа</span><b>${fmtMoney(c.workPay)}</b></div>${c.overtimeMinutes?`<div class="statline"><span>Переработка</span><b>${fmtHours(c.overtimeMinutes)} · ${fmtMoney(c.overtimePay)}</b></div>`:''}</div>`}).join(''):'<div class="empty">Смен пока нет</div>'}</div>`;document.querySelectorAll('[data-es]').forEach(b=>b.onclick=()=>openEmployeeShiftDetail(b.dataset.es))}
function openEmployeeShiftDetail(id){const s=shiftById(id),c=shiftCalc(s,s.ended_at||isoNow());modal(`<h3>Смена ${fmtDate(s.started_at)}</h3><div class="muted">${fmtTime(s.started_at)}–${s.ended_at?fmtTime(s.ended_at):'сейчас'} · ${statusText(s)}</div>${employeeSegmentsHTML(s)}<div class="card"><div class="statline"><span>Оплачиваемое время</span><b>${fmtHours(c.roundedMinutes)}</b></div><div class="statline"><span>Основная работа</span><b>${fmtMoney(c.basePay)}</b></div><div class="statline"><span>Переработка</span><b>${fmtHours(c.overtimeMinutes)} · ${fmtMoney(c.overtimePay)}</b></div><div class="statline"><span>Подтверждённые расходы</span><b>${fmtMoney(c.expenseApproved)}</b></div></div>`)}
function renderEmpMoney(){const l=employeeLedger(state.profile.id);document.getElementById('page').innerHTML=`<div class="section-title">Мои деньги</div><div class="kpis"><div class="kpi"><span>Заработано</span><b>${fmtMoney(l.earned)}</b></div><div class="kpi"><span>Расходы к возврату</span><b>${fmtMoney(l.approvedExpenses)}</b></div><div class="kpi"><span>Выплачено</span><b>${fmtMoney(l.paid)}</b></div><div class="kpi"><span>Осталось</span><b>${fmtMoney(l.due)}</b></div></div>${l.pending?`<div class="notice">Ещё на проверке: ${fmtMoney(l.pending)}</div>`:''}<div class="section-title">Последние выплаты</div><div class="list">${state.payments.filter(x=>x.employee_id===state.profile.id).slice(0,20).map(p=>`<div class="item"><div class="item-head"><div><b>${fmtDate(p.paid_at)}</b><div class="muted">${esc(p.comment||'Выплата')}</div></div><div class="money">${fmtMoney(p.amount)}</div></div></div>`).join('')||'<div class="empty">Выплат пока нет</div>'}</div>`}
function renderEmpProfile(){const r=payRuleFor(state.profile.id);document.getElementById('page').innerHTML=`<div class="section-title">Профиль</div><div class="card"><b>${esc(state.profile.full_name)}</b><div class="muted">${esc(state.profile.position||'Сотрудник')}</div></div><div class="section-title">Условия оплаты</div>${['base','project','other'].map(t=>{const [sf,of]=rateFields(t);return `<div class="item"><b>${SHIFT_TYPES[t]}</b><div class="statline"><span>Ставка за 10 часов</span><b>${fmtMoney(r[sf])}</b></div><div class="statline"><span>Переработка</span><b>${fmtMoney(r[of])}/ч</b></div></div>`}).join('')}<div class="notice">Тарифы изменяет только руководитель.</div>`}

// ---------- Todos ----------
function openTodos(managerMode){const me=state.profile.id;const relevant=managerMode?state.todos:state.todos.filter(t=>t.assignee_id===me);const sorted=[...relevant].sort((a,b)=>(a.completed-b.completed)||(PRIORITY_ORDER[a.priority]-PRIORITY_ORDER[b.priority])||(a.position-b.position)||new Date(a.created_at)-new Date(b.created_at));const assignees=managerMode?state.profiles.filter(p=>p.approved):[state.profile];modal(`<h3>Дела</h3><div class="field"><label>Новая задача</label><input id="todoTitle" placeholder="Что нужно сделать"></div><div class="row"><div class="field"><label>Приоритет</label><select id="todoPriority"><option value="high">Высокий</option><option value="normal" selected>Обычный</option><option value="low">Низкий</option></select></div>${managerMode?`<div class="field"><label>Кому</label><select id="todoAssignee">${assignees.map(p=>`<option value="${p.id}">${esc(p.full_name||p.email)}</option>`).join('')}</select></div>`:'<div></div>'}</div><button class="btn primary" id="todoAdd">+ ДОБАВИТЬ</button><div class="section-title">Список</div><div class="list">${sorted.length?sorted.map(t=>todoCard(t,managerMode)).join(''):'<div class="empty">Дел пока нет</div>'}</div>`);document.getElementById('todoAdd').onclick=()=>addTodo(managerMode);document.querySelectorAll('[data-todo-toggle]').forEach(b=>b.onclick=()=>toggleTodo(b.dataset.todoToggle,managerMode));document.querySelectorAll('[data-todo-up]').forEach(b=>b.onclick=()=>moveTodo(b.dataset.todoUp,-1,managerMode));document.querySelectorAll('[data-todo-down]').forEach(b=>b.onclick=()=>moveTodo(b.dataset.todoDown,1,managerMode));document.querySelectorAll('[data-todo-del]').forEach(b=>b.onclick=()=>deleteTodo(b.dataset.todoDel,managerMode))}
function todoCard(t,managerMode){const a=profileById(t.assignee_id);return `<div class="item priority-${t.priority} ${t.completed?'todo-done':''}"><div class="item-head"><div><b>${esc(t.title)}</b><div class="muted">${PRIORITY_LABEL[t.priority]}${managerMode?' · '+esc(a?.full_name|| (t.assignee_id===state.profile.id?'Вы':'Сотрудник')):''}</div></div><button class="btn small ${t.completed?'':'good'}" data-todo-toggle="${t.id}">${t.completed?'Вернуть':'Готово'}</button></div><div class="toolbar" style="margin-top:8px"><button class="btn small" data-todo-up="${t.id}">↑</button><button class="btn small" data-todo-down="${t.id}">↓</button>${(managerMode||t.created_by===state.profile.id)?`<button class="btn small danger" data-todo-del="${t.id}">Удалить</button>`:''}</div></div>`}
async function addTodo(managerMode){const title=document.getElementById('todoTitle').value.trim();if(!title)return;const assignee=managerMode?document.getElementById('todoAssignee').value:state.profile.id;const pos=Math.max(0,...state.todos.filter(t=>t.assignee_id===assignee).map(t=>Number(t.position)||0))+10;try{await q(sb.from('todos').insert({created_by:state.profile.id,assignee_id:assignee,title,priority:document.getElementById('todoPriority').value,position:pos}),'Дело');await loadAll();openTodos(managerMode)}catch(e){toast(e.message,'danger')}}
async function toggleTodo(id,mode){const t=state.todos.find(x=>x.id===id);try{await q(sb.from('todos').update({completed:!t.completed,completed_at:!t.completed?isoNow():null}).eq('id',id),'Дело');await loadAll();openTodos(mode)}catch(e){toast(e.message,'danger')}}
async function moveTodo(id,dir,mode){const t=state.todos.find(x=>x.id===id),list=state.todos.filter(x=>x.assignee_id===t.assignee_id&&!x.completed).sort((a,b)=>a.position-b.position),i=list.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=list.length)return;const other=list[j],a=t.position,b=other.position;try{await q(sb.from('todos').update({position:b}).eq('id',t.id),'Порядок дел');await q(sb.from('todos').update({position:a}).eq('id',other.id),'Порядок дел');await loadAll();openTodos(mode)}catch(e){toast(e.message,'danger')}}
async function deleteTodo(id,mode){if(!confirm('Удалить задачу?'))return;try{await q(sb.from('todos').delete().eq('id',id),'Удаление дела');await loadAll();openTodos(mode)}catch(e){toast(e.message,'danger')}}

// ---------- Manager dashboard/review ----------
function renderMgrDash(){const active=state.shifts.filter(s=>s.status==='active'),submitted=state.shifts.filter(s=>s.status==='submitted'),today=dateKey(new Date());let todayPay=0,todayExpenses=0;state.shifts.filter(s=>sameDay(s.started_at,today)).forEach(s=>{const c=shiftCalc(s,s.ended_at||isoNow());todayPay+=c.workPay;todayExpenses+=c.expenseVisible});document.getElementById('page').innerHTML=`<div class="section-title">Оперативная сводка</div><div class="section-sub">Обновляется автоматически. Последняя синхронизация ${state.lastSync?fmtTime(state.lastSync):'—'}.</div><div class="row"><button class="btn blue" id="mgrTodos">ДЕЛА</button><button class="btn" id="mgrRefresh">ОБНОВИТЬ</button></div><div class="kpis" style="margin-top:10px"><div class="kpi"><span>Работают сейчас</span><b>${active.length}</b></div><div class="kpi"><span>Смен на проверке</span><b>${submitted.length}</b></div><div class="kpi"><span>Работа сегодня</span><b>${fmtMoney(todayPay)}</b></div><div class="kpi"><span>Расходы сотрудников</span><b>${fmtMoney(todayExpenses)}</b></div></div><div class="section-title">Сейчас работают</div><div class="list">${active.length?active.map(managerShiftCard).join(''):'<div class="empty">Сейчас никто не работает</div>'}</div><div class="section-title">На проверке</div><div class="list">${submitted.length?submitted.map(managerShiftCard).join(''):'<div class="empty">Нет смен на проверке</div>'}</div><div class="section-title">Сегодня по проектам</div>${projectSummaryCards('today')}`;document.getElementById('mgrTodos').onclick=()=>openTodos(true);document.getElementById('mgrRefresh').onclick=async()=>{await loadAll();renderRole('mgrDash');toast('Обновлено')};document.querySelectorAll('[data-ms]').forEach(b=>b.onclick=()=>openManagerShift(b.dataset.ms))}
function managerShiftCard(s){const emp=profileById(s.employee_id),seg=activeSegmentFor(s.id)||segmentsFor(s.id).slice(-1)[0],c=shiftCalc(s,s.ended_at||isoNow());return `<div class="item clickable" data-ms="${s.id}"><div class="item-head"><div><b>${esc(emp?.full_name||emp?.email||'Сотрудник')}</b><div class="muted">${esc(projectById(seg?.project_id)?.name||'')} · ${esc(seg?.work_type||'')}</div></div><span class="status ${statusClass(s)}">${statusText(s)}</span></div><div class="statline"><span>${fmtHours(c.roundedMinutes)}${c.overtimeMinutes?' · переработка '+fmtHours(c.overtimeMinutes):''}</span><b>${fmtMoney(c.workPay)}</b></div></div>`}
function openManagerShift(id){const sh=shiftById(id);if(!sh)return;const c=shiftCalc(sh,sh.ended_at||isoNow()),emp=profileById(sh.employee_id),ss=segmentsFor(id),ee=expensesFor(id);modal(`<h3>${esc(emp?.full_name||'Сотрудник')} · ${fmtDate(sh.started_at)}</h3><div class="muted">${fmtTime(sh.started_at)}–${sh.ended_at?fmtTime(sh.ended_at):'сейчас'} · ${statusText(sh)}</div><div class="kpis"><div class="kpi"><span>Оплачиваемое время</span><b>${fmtHours(c.roundedMinutes)}</b></div><div class="kpi"><span>Работа</span><b>${fmtMoney(c.workPay)}</b></div><div class="kpi"><span>Переработка</span><b>${fmtMoney(c.overtimePay)}</b><span class="mini">${fmtHours(c.overtimeMinutes)}</span></div><div class="kpi"><span>Расходы</span><b>${fmtMoney(c.expenseVisible)}</b></div></div><div class="section-title">Участки смены</div><div class="list">${ss.map(s=>managerSegmentCard(s)).join('')||'<div class="empty">Нет участков</div>'}</div><div class="section-title">Расходы сотрудника</div><div class="list">${ee.map(managerExpenseCard).join('')||'<div class="empty">Расходов нет</div>'}</div>${sh.status==='submitted'?`<div class="field"><label>Комментарий руководителя по смене</label><textarea id="mgrShiftNote">${esc(sh.manager_note||'')}</textarea></div><button class="btn good" id="approveShift">ПОДТВЕРДИТЬ СМЕНУ</button>`:''}`);document.querySelectorAll('[data-edit-msseg]').forEach(b=>b.onclick=()=>openManagerSegmentEdit(b.dataset.editMsseg,id));document.querySelectorAll('[data-review-exp]').forEach(b=>b.onclick=()=>openExpenseReview(b.dataset.reviewExp,id));const a=document.getElementById('approveShift');if(a)a.onclick=()=>approveShift(sh)}
function managerSegmentCard(s){const base=segmentBaseRate(s),over=segmentOvertimeRate(s);return `<div class="item"><div class="item-head"><div><b>${fmtTime(s.started_at)}–${s.ended_at?fmtTime(s.ended_at):'сейчас'}</b><div class="muted">${esc(projectById(s.project_id)?.name||'')} · ${esc(s.work_type)} · ${SHIFT_TYPES[s.shift_type||'base']}</div></div><button class="btn small" data-edit-msseg="${s.id}">Править</button></div><div class="mini muted">Ставка 10 ч: ${fmtMoney(base)} · переработка ${fmtMoney(over)}/ч</div>${s.employee_comment?`<div class="comment"><strong>Сотрудник</strong>${esc(s.employee_comment)}</div>`:''}${s.manager_reply?`<div class="comment manager"><strong>Руководитель</strong>${esc(s.manager_reply)}</div>`:''}</div>`}
function managerExpenseCard(e){return `<div class="item"><div class="item-head"><div><b>${esc(e.employee_category)}</b><div class="muted">${esc(projectById(e.project_id)?.name||'')} · аналитика: ${esc(e.analytics_category)}</div></div><div><div class="money">${fmtMoney(e.amount)}</div><span class="status ${e.status==='approved'?'good':e.status==='rejected'?'danger':'warn'}">${e.status==='approved'?'Принят':e.status==='rejected'?'Отклонён':'Проверить'}</span></div></div>${e.comment?`<div class="comment">${esc(e.comment)}</div>`:''}<button class="btn small" data-review-exp="${e.id}" style="margin-top:8px">Разнести расход</button></div>`}
function openManagerSegmentEdit(id,shiftId){const s=state.segments.find(x=>x.id===id);modal(`<h3>Правка участка</h3><div class="field"><label>Проект</label><select id="msProject">${projectOptions(s.project_id)}</select></div><div class="field"><label>Вид работы</label><select id="msWork">${workOptions(s.work_type)}</select></div><div class="field"><label>Тип смены</label><select id="msType">${typeOptions(s.shift_type)}</select></div><div class="field"><label>Ставка за 10 часов, грн</label><input id="msBase" type="number" value="${s.manager_base_rate_override??segmentBaseRate(s)}"><div class="hint">Если изменить — ставка фиксируется именно для этого участка.</div></div><div class="field"><label>Переработка, грн/час</label><input id="msOver" type="number" value="${s.manager_overtime_rate_override??segmentOvertimeRate(s)}"></div><div class="field"><label>Ответ/дополнение к комментарию сотрудника</label><textarea id="msReply">${esc(s.manager_reply||'')}</textarea></div><button class="btn primary" id="msSave">СОХРАНИТЬ</button>`);document.getElementById('msSave').onclick=async()=>{try{await q(sb.from('shift_segments').update({project_id:document.getElementById('msProject').value,work_type:document.getElementById('msWork').value,shift_type:document.getElementById('msType').value,manager_base_rate_override:Number(document.getElementById('msBase').value)||0,manager_overtime_rate_override:Number(document.getElementById('msOver').value)||0,manager_reply:document.getElementById('msReply').value.trim()}).eq('id',id),'Правка участка');await loadAll();closeModal();openManagerShift(shiftId)}catch(e){toast(e.message,'danger')}}}
function openExpenseReview(id,shiftId){const e=state.expenses.find(x=>x.id===id);modal(`<h3>Разнести расход</h3><div class="notice"><b>${esc(e.employee_category)}</b> · ${fmtMoney(e.amount)}<br>${esc(e.comment||'Без комментария')}</div><div class="field"><label>Статья аналитики</label><select id="erCat">${ANALYTICS_CATS.filter(x=>x!=='Сотрудники').map(x=>`<option ${x===e.analytics_category?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Статус</label><select id="erStatus"><option value="pending" ${e.status==='pending'?'selected':''}>На проверке</option><option value="approved" ${e.status==='approved'?'selected':''}>Подтвердить</option><option value="rejected" ${e.status==='rejected'?'selected':''}>Отклонить</option></select></div><div class="field"><label>Комментарий руководителя</label><textarea id="erNote">${esc(e.manager_note||'')}</textarea></div><button class="btn primary" id="erSave">СОХРАНИТЬ</button>`);document.getElementById('erSave').onclick=async()=>{try{await q(sb.from('expenses').update({analytics_category:document.getElementById('erCat').value,status:document.getElementById('erStatus').value,manager_note:document.getElementById('erNote').value.trim()}).eq('id',id),'Разнос расхода');await loadAll();closeModal();openManagerShift(shiftId)}catch(e){toast(e.message,'danger')}}}
async function approveShift(sh){const pending=expensesFor(sh.id).filter(e=>e.status==='pending').length;if(pending&&!confirm(`У смены ${pending} расход(а) ещё на проверке. Подтвердить смену без них?`))return;try{await q(sb.from('shifts').update({status:'approved',manager_note:document.getElementById('mgrShiftNote')?.value.trim()||'',approved_by:state.profile.id,approved_at:isoNow()}).eq('id',sh.id),'Подтверждение смены');closeModal();await loadAll();renderRole('mgrDash');toast('Смена подтверждена')}catch(e){toast(e.message,'danger')}}

// ---------- Manager projects/people/finance ----------
function renderMgrProjects(){document.getElementById('page').innerHTML=`<div class="section-title">Проекты</div><button class="btn primary" id="addProject">+ НОВЫЙ ПРОЕКТ</button><div class="list" style="margin-top:10px">${state.projects.map(projectCard).join('')||'<div class="empty">Проектов нет</div>'}</div>`;document.getElementById('addProject').onclick=openAddProject;document.querySelectorAll('[data-pr-toggle]').forEach(b=>b.onclick=()=>toggleProject(b.dataset.prToggle));document.querySelectorAll('[data-pr-cost]').forEach(b=>b.onclick=()=>openProjectCost(b.dataset.prCost));document.querySelectorAll('[data-pr-money]').forEach(b=>b.onclick=()=>openProjectMoney(b.dataset.prMoney));document.querySelectorAll('[data-pr-rate]').forEach(b=>b.onclick=()=>openProjectRates(b.dataset.prRate));document.querySelectorAll('[data-pr-report]').forEach(b=>b.onclick=()=>openProjectReport(b.dataset.prReport,'all'))}
function projectCard(p){const a=projectAnalytics(p.id,'all');return `<div class="item"><div class="item-head"><div><b>${esc(p.name)}</b><div class="muted">${p.active?'Активный':'Завершён'}</div></div><span class="status ${p.active?'good':''}">${p.active?'В работе':'Архив'}</span></div><div class="statline"><span>Получено / затраты</span><b>${fmtMoney(a.received)} / ${fmtMoney(a.totalCosts)}</b></div><div class="toolbar"><button class="btn small" data-pr-report="${p.id}">Сводка</button><button class="btn small" data-pr-cost="${p.id}">+ Затрата</button><button class="btn small" data-pr-money="${p.id}">+ Деньги</button><button class="btn small" data-pr-rate="${p.id}">Переработки</button><button class="btn small" data-pr-toggle="${p.id}">${p.active?'Завершить':'Возобновить'}</button></div></div>`}
function openAddProject(){modal(`<h3>Новый проект</h3><div class="field"><label>Название</label><input id="prName"></div><button class="btn primary" id="prSave">СОЗДАТЬ</button>`);document.getElementById('prSave').onclick=async()=>{const name=document.getElementById('prName').value.trim();if(!name)return;try{await q(sb.from('projects').insert({name,created_by:state.profile.id}),'Проект');closeModal();await loadAll();renderRole('mgrProjects')}catch(e){toast(e.message,'danger')}}}
async function toggleProject(id){const p=projectById(id);await q(sb.from('projects').update({active:!p.active}).eq('id',id),'Проект');await loadAll();renderRole('mgrProjects')}
function openProjectCost(pid){modal(`<h3>Затрата проекта · ${esc(projectById(pid)?.name||'')}</h3><div class="field"><label>Категория</label><select id="pcCat">${DIRECT_COST_CATS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Сумма, грн</label><input id="pcAmount" type="number"></div><div class="field"><label>Комментарий</label><textarea id="pcComment"></textarea></div><button class="btn primary" id="pcSave">СОХРАНИТЬ</button>`);document.getElementById('pcSave').onclick=async()=>{const amount=Number(document.getElementById('pcAmount').value);if(!(amount>0))return;try{await q(sb.from('project_costs').insert({project_id:pid,category:document.getElementById('pcCat').value,amount,comment:document.getElementById('pcComment').value.trim(),created_by:state.profile.id}),'Затрата');closeModal();await loadAll();renderRole('mgrProjects')}catch(e){toast(e.message,'danger')}}}
function openProjectMoney(pid){modal(`<h3>Деньги проекта · ${esc(projectById(pid)?.name||'')}</h3><div class="field"><label>Тип</label><select id="pmType"><option value="estimate">Сметная сумма</option><option value="received">Получено денег</option></select></div><div class="field"><label>Сумма, грн</label><input id="pmAmount" type="number"></div><div class="field"><label>Комментарий</label><textarea id="pmComment"></textarea></div><button class="btn primary" id="pmSave">СОХРАНИТЬ</button>`);document.getElementById('pmSave').onclick=async()=>{const amount=Number(document.getElementById('pmAmount').value);if(!(amount>0))return;try{await q(sb.from('project_money').insert({project_id:pid,entry_type:document.getElementById('pmType').value,amount,comment:document.getElementById('pmComment').value.trim(),created_by:state.profile.id}),'Деньги проекта');closeModal();await loadAll();renderRole('mgrProjects')}catch(e){toast(e.message,'danger')}}}
function openProjectRates(pid){const employees=state.profiles.filter(p=>p.role==='employee'&&p.approved);modal(`<h3>Переработки · ${esc(projectById(pid)?.name||'')}</h3><div class="field"><label>Сотрудник</label><select id="porEmp">${employees.map(e=>`<option value="${e.id}">${esc(e.full_name||e.email)}</option>`).join('')}</select></div><div class="field"><label>Тип смены</label><select id="porType">${typeOptions('base')}</select></div><div class="field"><label>Ставка переработки, грн/ч</label><input id="porRate" type="number"></div><button class="btn primary" id="porSave">СОХРАНИТЬ</button><div class="section-title">Заданные ставки</div><div class="list">${state.projectRates.filter(x=>x.project_id===pid).map(x=>`<div class="item"><b>${esc(profileById(x.employee_id)?.full_name||'Сотрудник')}</b><div class="muted">${SHIFT_TYPES[x.shift_type]} · ${fmtMoney(x.overtime_rate)}/ч</div></div>`).join('')||'<div class="empty">Переопределений нет</div>'}</div>`);document.getElementById('porSave').onclick=async()=>{const row={project_id:pid,employee_id:document.getElementById('porEmp').value,shift_type:document.getElementById('porType').value,overtime_rate:Number(document.getElementById('porRate').value)||0};try{await q(sb.from('project_overtime_rates').upsert(row,{onConflict:'project_id,employee_id,shift_type'}),'Ставка переработки');await loadAll();openProjectRates(pid)}catch(e){toast(e.message,'danger')}}}

function renderMgrPeople(){const pending=state.profiles.filter(p=>p.role==='employee'&&!p.approved),approved=state.profiles.filter(p=>p.role==='employee'&&p.approved);document.getElementById('page').innerHTML=`<div class="section-title">Запросы доступа</div><div class="list">${pending.map(p=>`<div class="item"><div class="item-head"><div><b>${esc(p.full_name||p.email)}</b><div class="muted">${esc(p.email||'')}</div></div><button class="btn small good" data-approve="${p.id}">Разрешить</button></div></div>`).join('')||'<div class="empty">Новых заявок нет</div>'}</div><div class="section-title">Сотрудники</div><div class="list">${approved.map(employeeCard).join('')||'<div class="empty">Сотрудников нет</div>'}</div>`;document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approveUser(b.dataset.approve));document.querySelectorAll('[data-rule]').forEach(b=>b.onclick=()=>openPayRule(b.dataset.rule));document.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>openPayment(b.dataset.pay));document.querySelectorAll('[data-emp-report]').forEach(b=>b.onclick=()=>openEmployeeReport(b.dataset.empReport))}
function employeeCard(e){const l=employeeLedger(e.id);return `<div class="item"><div class="item-head"><div><b>${esc(e.full_name||e.email)}</b><div class="muted">${esc(e.position||'Сотрудник')}</div></div><span class="status">${fmtMoney(l.due)}</span></div><div class="toolbar"><button class="btn small" data-rule="${e.id}">Тарифы</button><button class="btn small good" data-pay="${e.id}">Выплата</button><button class="btn small" data-emp-report="${e.id}">Сводка</button></div></div>`}
async function approveUser(id){try{await q(sb.from('profiles').update({approved:true}).eq('id',id),'Доступ');await q(sb.from('pay_rules').upsert({employee_id:id,standard_hours:10}),'Тариф');await loadAll();renderRole('mgrPeople')}catch(e){toast(e.message,'danger')}}
function openPayRule(empId){const r=payRuleFor(empId),e=profileById(empId);modal(`<h3>Тарифы · ${esc(e?.full_name||'')}</h3><div class="notice">Полная ставка рассчитана на 10 часов. До 10 часов оплата пропорциональна фактически отработанному времени; после 10 часов — переработка.</div>${['base','project','other'].map(t=>{const [sf,of]=rateFields(t);return `<div class="card"><b>${SHIFT_TYPES[t]}</b><div class="row"><div class="field"><label>Смена 10 ч, грн</label><input id="r_${sf}" type="number" value="${Number(r[sf])||0}"></div><div class="field"><label>Переработка, грн/ч</label><input id="r_${of}" type="number" value="${Number(r[of])||0}"></div></div></div>`}).join('')}<div class="row"><div class="field"><label>Минимальный отдых, ч</label><input id="r_rest" type="number" value="${Number(r.rest_threshold_hours)||8}"></div><div class="field"><label>Компенсация короткого отдыха</label><input id="r_bonus" type="number" value="${Number(r.short_rest_bonus)||0}"></div></div><button class="btn primary" id="rSave">СОХРАНИТЬ</button>`);document.getElementById('rSave').onclick=async()=>{const row={employee_id:empId,standard_hours:10,rest_threshold_hours:Number(document.getElementById('r_rest').value)||8,short_rest_bonus:Number(document.getElementById('r_bonus').value)||0};['base','project','other'].forEach(t=>{const [sf,of]=rateFields(t);row[sf]=Number(document.getElementById('r_'+sf).value)||0;row[of]=Number(document.getElementById('r_'+of).value)||0});try{await q(sb.from('pay_rules').upsert(row),'Тарифы');closeModal();await loadAll();renderRole('mgrPeople')}catch(e){toast(e.message,'danger')}}}
function openPayment(empId){const e=profileById(empId),l=employeeLedger(empId);modal(`<h3>Выплата · ${esc(e?.full_name||'')}</h3><div class="notice">Сейчас осталось: <b>${fmtMoney(l.due)}</b></div><div class="field"><label>Сумма, грн</label><input id="payAmount" type="number"></div><div class="field"><label>Комментарий</label><input id="payComment" placeholder="Аванс, зарплата..."></div><button class="btn primary" id="paySave">ЗАПИСАТЬ ВЫПЛАТУ</button>`);document.getElementById('paySave').onclick=async()=>{const amount=Number(document.getElementById('payAmount').value);if(!(amount>0))return;try{await q(sb.from('employee_payments').insert({employee_id:empId,amount,comment:document.getElementById('payComment').value.trim(),created_by:state.profile.id}),'Выплата');closeModal();await loadAll();renderRole('mgrPeople')}catch(e){toast(e.message,'danger')}}}

function renderMgrFinance(){document.getElementById('page').innerHTML=`<div class="section-title">Финансы</div><div class="section-sub">Выплаты сотрудникам и поступления проектов добавляются из карточек сотрудников/проектов.</div><div class="section-title">Последние выплаты</div><div class="list">${state.payments.slice(0,20).map(p=>`<div class="item"><div class="item-head"><div><b>${esc(profileById(p.employee_id)?.full_name||'Сотрудник')}</b><div class="muted">${fmtDate(p.paid_at)} · ${esc(p.comment||'Выплата')}</div></div><div class="money">${fmtMoney(p.amount)}</div></div></div>`).join('')||'<div class="empty">Выплат нет</div>'}</div><div class="section-title">Последние деньги проектов</div><div class="list">${state.projectMoney.slice(0,20).map(x=>`<div class="item"><div class="item-head"><div><b>${esc(projectById(x.project_id)?.name||'')}</b><div class="muted">${fmtDate(x.entry_at)} · ${x.entry_type==='received'?'Получено':'Смета'}</div></div><div class="money">${fmtMoney(x.amount)}</div></div></div>`).join('')||'<div class="empty">Записей нет</div>'}</div>`}

// ---------- Analytics ----------
function periodMatch(v,period){return period==='today'?sameDay(v):true}
function projectAnalytics(pid,period='all'){
 let labor=0,employeeExpenses=0,direct=0,received=0,estimate=0;const categories={};ANALYTICS_CATS.forEach(k=>categories[k]=0);const employees={};
 state.shifts.filter(s=>s.status==='approved'&&periodMatch(s.started_at,period)).forEach(sh=>{const c=shiftCalc(sh,sh.ended_at),p=c.perProject[pid];if(p){const lp=p.basePay+p.overtimePay+(p.restBonus||0);labor+=lp;categories.Сотрудники+=lp;employees[sh.employee_id]=(employees[sh.employee_id]||0)+lp}});
 state.expenses.filter(e=>e.project_id===pid&&e.status==='approved'&&periodMatch(e.created_at,period)).forEach(e=>{employeeExpenses+=Number(e.amount)||0;categories[e.analytics_category]=(categories[e.analytics_category]||0)+Number(e.amount||0)});
 state.projectCosts.filter(c=>c.project_id===pid&&periodMatch(c.cost_at,period)).forEach(c=>{direct+=Number(c.amount)||0;categories[c.category]=(categories[c.category]||0)+Number(c.amount||0)});
 state.projectMoney.filter(x=>x.project_id===pid&&periodMatch(x.entry_at,period)).forEach(x=>{if(x.entry_type==='received')received+=Number(x.amount)||0;else estimate+=Number(x.amount)||0});
 const totalCosts=labor+employeeExpenses+direct;return {labor,employeeExpenses,direct,received,estimate,totalCosts,balance:received-totalCosts,categories,employees};
}
function globalAnalytics(period='all'){let received=0,estimate=0,totalCosts=0,labor=0,employeeExpenses=0,direct=0;state.projects.forEach(p=>{const a=projectAnalytics(p.id,period);received+=a.received;estimate+=a.estimate;totalCosts+=a.totalCosts;labor+=a.labor;employeeExpenses+=a.employeeExpenses;direct+=a.direct});const paid=state.payments.filter(p=>periodMatch(p.paid_at,period)).reduce((a,p)=>a+Number(p.amount||0),0),owed=state.profiles.filter(p=>p.role==='employee'&&p.approved).reduce((a,e)=>a+Math.max(0,employeeLedger(e.id).due),0);return {received,estimate,totalCosts,labor,employeeExpenses,direct,paid,owed,balance:received-totalCosts}}
function projectSummaryCards(period){return `<div class="list">${state.projects.map(p=>{const a=projectAnalytics(p.id,period);return `<div class="item clickable" data-pa="${p.id}"><div class="item-head"><b>${esc(p.name)}</b><span class="status ${a.balance>=0?'good':'danger'}">${fmtMoney(a.balance)}</span></div><div class="statline"><span>Получено / затраты</span><b>${fmtMoney(a.received)} / ${fmtMoney(a.totalCosts)}</b></div></div>`}).join('')||'<div class="empty">Проектов нет</div>'}</div>`}
function renderMgrAnalytics(){document.getElementById('page').innerHTML=`<div class="section-title">Расширенная аналитика</div><div class="filterbar"><button class="chip active" data-period="all">За всё время</button><button class="chip" data-period="today">Сегодня</button></div><div id="anBody"></div>`;let period='all';const draw=()=>{const g=globalAnalytics(period);document.getElementById('anBody').innerHTML=`<div class="section-title">Баланс мастерской</div><div class="kpis"><div class="kpi"><span>Получено</span><b>${fmtMoney(g.received)}</b></div><div class="kpi"><span>Сметы</span><b>${fmtMoney(g.estimate)}</b></div><div class="kpi"><span>Все затраты</span><b>${fmtMoney(g.totalCosts)}</b></div><div class="kpi"><span>Баланс</span><b class="${g.balance>=0?'positive':'negative'}">${fmtMoney(g.balance)}</b></div></div><div class="card"><div class="statline"><span>Труд сотрудников</span><b>${fmtMoney(g.labor)}</b></div><div class="statline"><span>Расходы сотрудников</span><b>${fmtMoney(g.employeeExpenses)}</b></div><div class="statline"><span>Прямые расходы проектов</span><b>${fmtMoney(g.direct)}</b></div><div class="statline"><span>Выплачено сотрудникам</span><b>${fmtMoney(g.paid)}</b></div><div class="statline"><span>Осталось сотрудникам</span><b>${fmtMoney(g.owed)}</b></div></div><div class="section-title">По проектам</div>${projectSummaryCards(period)}<div class="section-title">По сотрудникам</div><div class="list">${state.profiles.filter(p=>p.role==='employee'&&p.approved).map(e=>{const l=employeeLedger(e.id);return `<div class="item clickable" data-ear="${e.id}"><div class="item-head"><b>${esc(e.full_name||e.email)}</b><span class="status">${fmtMoney(l.due)}</span></div><div class="statline"><span>Заработано / выплачено</span><b>${fmtMoney(l.earned+l.approvedExpenses)} / ${fmtMoney(l.paid)}</b></div></div>`}).join('')}</div>`;document.querySelectorAll('[data-pa]').forEach(b=>b.onclick=()=>openProjectReport(b.dataset.pa,period));document.querySelectorAll('[data-ear]').forEach(b=>b.onclick=()=>openEmployeeReport(b.dataset.ear))};document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x.dataset.period===period));draw()});draw()}
function openProjectReport(pid,period='all'){const p=projectById(pid),a=projectAnalytics(pid,period),cats=Object.entries(a.categories).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]),emps=Object.entries(a.employees).sort((a,b)=>b[1]-a[1]);modal(`<h3>${esc(p?.name||'Проект')}</h3><div class="muted">${period==='today'?'Сегодня':'За всё время'}</div><div class="kpis"><div class="kpi"><span>Получено</span><b>${fmtMoney(a.received)}</b></div><div class="kpi"><span>Смета</span><b>${fmtMoney(a.estimate)}</b></div><div class="kpi"><span>Затраты</span><b>${fmtMoney(a.totalCosts)}</b></div><div class="kpi"><span>Баланс</span><b class="${a.balance>=0?'positive':'negative'}">${fmtMoney(a.balance)}</b></div></div><div class="section-title">Затраты по статьям</div><div class="list">${cats.map(([k,v])=>`<div class="item"><div class="item-head"><b>${esc(k)}</b><div class="money">${fmtMoney(v)}</div></div></div>`).join('')||'<div class="empty">Затрат нет</div>'}</div><div class="section-title">Сотрудники</div><div class="list">${emps.map(([id,v])=>`<div class="item"><div class="item-head"><b>${esc(profileById(id)?.full_name||'Сотрудник')}</b><div class="money">${fmtMoney(v)}</div></div></div>`).join('')||'<div class="empty">Начислений нет</div>'}</div>`)}
function openEmployeeReport(empId){const e=profileById(empId),l=employeeLedger(empId),shifts=state.shifts.filter(s=>s.employee_id===empId&&s.status==='approved');const byProject={};shifts.forEach(s=>{const c=shiftCalc(s,s.ended_at);Object.entries(c.perProject).forEach(([pid,v])=>byProject[pid]=(byProject[pid]||0)+v.basePay+v.overtimePay+(v.restBonus||0))});modal(`<h3>${esc(e?.full_name||'Сотрудник')}</h3><div class="kpis"><div class="kpi"><span>Заработано</span><b>${fmtMoney(l.earned)}</b></div><div class="kpi"><span>Расходы</span><b>${fmtMoney(l.approvedExpenses)}</b></div><div class="kpi"><span>Выплачено</span><b>${fmtMoney(l.paid)}</b></div><div class="kpi"><span>Осталось</span><b>${fmtMoney(l.due)}</b></div></div><div class="section-title">По проектам</div><div class="list">${Object.entries(byProject).sort((a,b)=>b[1]-a[1]).map(([pid,v])=>`<div class="item"><div class="item-head"><b>${esc(projectById(pid)?.name||'')}</b><div class="money">${fmtMoney(v)}</div></div></div>`).join('')||'<div class="empty">Нет данных</div>'}</div>`)}

window.addEventListener('online',()=>scheduleRefresh());
window.addEventListener('offline',()=>toast('Нет сети. Просмотр доступен, изменения лучше вносить после восстановления связи.','danger'));
if('serviceWorker' in navigator&&/^https?:/.test(location.protocol))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
init();
})();
